# Health metrics
mqtt:
  sensor:
    - name: system_state_192_168_0_5
      state_topic: "instance/192.168.0.5/sensor/system/state"
    - name: system_state_192_168_0_6
      state_topic: "instance/192.168.0.6/sensor/system/state"

template:
  - sensor:
      - default_entity_id: sensor.system_state
        state: >-
          {% set ip = states("sensor.local_ip") | replace(".", "_") %}
          {% set sensor_name = "sensor.system_state_" + ip %}
          {{ states(sensor_name) }}
        name: system_state

automation:
  - id: system_start
    alias: Система - запуск
    initial_state: true
    trigger:
      - trigger: homeassistant
        event: start
    action:
      - action: mqtt.publish
        data_template:
          topic: "instance/{{ states('sensor.local_ip') }}/sensor/system/state"
          payload: "starting"
          retain: true
      - delay: 00:00:10
      - action: mqtt.publish
        data_template:
          topic: "instance/{{ states('sensor.local_ip') }}/sensor/system/state"
          payload: "running"
          retain: true

  - id: system_shutdown
    alias: Система - выключение
    initial_state: true
    trigger:
      - trigger: homeassistant
        event: shutdown
    action:
      - action: mqtt.publish
        data_template:
          topic: "instance/{{ states('sensor.local_ip') }}/sensor/system/state"
          payload: "shutdown"
          retain: true

  - id: system_keepalive
    alias: Система - периодическое состояние
    initial_state: true
    trigger:
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
      - trigger: state
        entity_id: sensor.time_date
    action:
      - action: mqtt.publish
        data_template:
          topic: "instance/{{ states('sensor.local_ip') }}/sensor/keepalive/state"
          payload: "{{ now() }}"
          retain: true

  - id: system_unexpected_reboot
    alias: Система - неожиданная перезагрузка
    initial_state: true
    trigger:
      - trigger: state
        entity_id: sensor.system_state
        from: "running"
        to: "starting"
    action:
      - action: mqtt.publish
        data_template:
          topic: "instance/{{ states('sensor.local_ip') }}/sensor/unexpected_reboot"
          payload: "1"
          retain: false
