homeassistant:
  customize:
    sensor.blood_sugar_mmol:
      friendly_name: Сахар крови

template:
  - sensor:
      - name: blood_sugar_mmol
        state: >-
          {{(states('sensor.blood_sugar') | int / 18) | round(1, 'floor')}}

automation:
  - id: wakeup_at_night
    alias: Разбудить ночью при гипогликемии
    trigger:
      - platform: numeric_state
        entity_id: sensor.blood_sugar_mmol
        below: 4
    condition:
      - alias: "sound controller"
        condition: state
        entity_id: binary_sensor.sound_control
        state: "on"
      - alias: "it is night"
        condition: state
        entity_id: binary_sensor.night
        state: "on"
      - alias: "only when Yuri is at home"
        condition: state
        entity_id: person.yuri_vashchenko
        state: "home"
    action:
      - alias: call_elena_yandex_station_say
        service: script.turn_on
        target:
          entity_id: script.elena_yandex_station_say
        data_template:
          variables:
            message: "Внимание! Гипогликемия! Срочно съешь что-нибудь"
            volume: 50
      - wait_for_trigger:
          - platform: numeric_state
            entity_id: sensor.blood_sugar_mmol
            above: 4
    mode: single
    max_exceeded: silent
  - id: hi_bg
    alias: Очень высокий сахар - возможно что-то с сенсором?
    trigger:
      - platform: numeric_state
        entity_id: sensor.blood_sugar_mmol
        above: 19.99
    condition:
      - alias: "sound controller"
        condition: state
        entity_id: binary_sensor.sound_control
        state: "on"
    action:
      - alias: call_elena_yandex_station_say
        service: script.turn_on
        target:
          entity_id: script.elena_yandex_station_say
        data_template:
          variables:
            message: "Внимание! Очень высокий сахар! Возможно сенсор не работает"
            volume: 80
      - wait_for_trigger:
          - platform: numeric_state
            entity_id: sensor.blood_sugar_mmol
            below: 15
    mode: single
    max_exceeded: silent
