homeassistant:
  customize:
    sensor.blood_sugar_mmol:
      friendly_name: Сахар крови

template:
  - sensor:
      - name: blood_sugar_mmol
        state: >-
          {{(states('sensor.blood_sugar') | int / 18) | round(1, 'floor')}}

automation:
  - id: nightscout_wakeup_at_night
    alias: Мониторинг глюкозы - разбудить ночью при гипогликемии
    trigger:
      - trigger: numeric_state
        entity_id: sensor.blood_sugar_mmol
        below: 4
    condition:
      - alias: Проверка контроля звука
        condition: state
        entity_id: binary_sensor.sound_control
        state: "on"
      - alias: Проверка времени суток
        condition: state
        entity_id: binary_sensor.night
        state: "on"
      - alias: Проверка присутствия
        condition: state
        entity_id: person.yuri_vashchenko
        state: "home"
    action:
      - alias: Озвучка предупреждения
        action: script.turn_on
        target:
          entity_id: script.elena_yandex_station_say
        data_template:
          variables:
            message: Внимание! Гипогликемия! Срочно съешь что-нибудь
            volume: 40
      - wait_for_trigger:
          - trigger: numeric_state
            entity_id: sensor.blood_sugar_mmol
            above: 5
    mode: single
    max_exceeded: silent
  - id: nightscout_high_blood_glucose
    alias: Мониторинг глюкозы - очень высокий сахар
    trigger:
      - trigger: numeric_state
        entity_id: sensor.blood_sugar_mmol
        above: 19.99
    condition:
      - alias: Проверка контроля звука
        condition: state
        entity_id: binary_sensor.sound_control
        state: "on"
      - alias: Проверка присутствия
        condition: state
        entity_id: person.yuri_vashchenko
        state: "home"
    action:
      - alias: Озвучка предупреждения
        action: script.turn_on
        target:
          entity_id: script.elena_yandex_station_say
        data_template:
          variables:
            message: Внимание! Очень высокий сахар! Возможно сенсор не работает
            volume: 40
      - wait_for_trigger:
          - trigger: numeric_state
            entity_id: sensor.blood_sugar_mmol
            below: 15
    mode: single
    max_exceeded: silent
