# Recorder
# https://www.home-assistant.io/integrations/recorder

recorder:
  db_url: !secret mariadb_url
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - light
    #entities: 
  exclude:    # Eliminate anything that you never graph or refer back to
    domains:
      - automation
      - updater
      - weather # Ignore weather
    entities:
      - sun.sun
      - sensor.season
      - sensor.time

automation:
  - id: Сжатие базы
    alias: database_purge_everyday
    initial_state: true
    trigger:
      - platform: time
        at: '01:00:00'
    action:
      - service: recorder.purge
        data:
          keep_days: 30
          repack: true