# Updater
# https://www.home-assistant.io/integrations/updater

updater:

# notifier
automation:
  - alias: "Update Available Notification"
    trigger:
      - platform: state
        entity_id: binary_sensor.updater
        from: "off"
        to: "on"
    action:
      - service: notify.notify
        data_template:
          message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."