# Utility meter
# https://www.home-assistant.io/integrations/utility_meter

homeassistant:
  customize:
    sensor.current_energy_cost:
      friendly_name: Текущая стоимость
    sensor.daily_energy_total_cost_single_tariff:
      friendly_name: Всего за день по одноставочному тарифу
    sensor.monthly_energy_total_cost_single_tariff:
      friendly_name: Всего за месяц по одноставочному тарифу
    sensor.daily_energy_total_cost_double_tariff:
      friendly_name: Всего за день по двуставочному тарифу
    sensor.monthly_energy_total_cost_double_tariff:
      friendly_name: Всего за месяц по двуставочному тарифу

mqtt:
  number:
    - object_id: energy_single_tariff
      name: Одноставочный тариф
      command_topic: home/system/settings/energy/tariffs/single
      entity_category: config
      min: 0.0
      max: 20.0
      step: 0.01
      retain: true
      icon: mdi:cash-100
    - object_id: energy_day_tariff
      name: Дневной тариф
      command_topic: home/system/settings/energy/tariffs/day
      entity_category: config
      min: 0.0
      max: 20.0
      step: 0.01
      icon: mdi:cash-100
      retain: true
    - object_id: energy_night_tariff
      name: Ночной тариф
      command_topic: home/system/settings/energy/tariffs/night
      entity_category: config
      min: 0.0
      max: 20.0
      step: 0.01
      icon: mdi:cash-100
      retain: true

template:
  - sensor:
      - name: current_energy_cost
        device_class: monetary
        icon: mdi:cash-100
        unit_of_measurement: "RUB/kWh"
        state: >
          {{ states("number.energy_single_tariff") | float }}
        # {% if is_state("utility_meter.daily_energy", "day") -%}
        #   {{ states("number.energy_day_tariff") | float }}
        # {% elif is_state("utility_meter.daily_energy", "night") -%}
        #   {{ states("number.energy_night_tariff") | float }}
        # {%- endif %}
      - name: daily_energy_total_cost_single_tariff
        device_class: monetary
        icon: mdi:cash-100
        unit_of_measurement: "RUB"
        state: |
          {% set d_day = states("sensor.daily_energy_day") | float %}
          {% set d_night = states("sensor.daily_energy_night") | float %}
          {{ ((d_day + d_night) * (states("number.energy_single_tariff") | float)) | round(2) }}
      - name: monthly_energy_total_cost_single_tariff
        device_class: monetary
        icon: mdi:cash-100
        unit_of_measurement: "RUB"
        state: |
          {% set m_day = states("sensor.monthly_energy_day") | float %}
          {% set m_night = states("sensor.monthly_energy_night") | float %}
          {{ ((m_day + m_night) * states("number.energy_single_tariff") | float) | round(2) }}
      - name: daily_energy_total_cost_double_tariff
        device_class: monetary
        icon: mdi:cash-100
        unit_of_measurement: "RUB"
        state: |
          {% set d_day = states("sensor.daily_energy_day") | float %}
          {% set d_night = states("sensor.daily_energy_night") | float %}
          {{ ((d_day * states("number.energy_day_tariff") | float) + (d_night * states("number.energy_night_tariff") | float)) | round(2) }}
      - name: monthly_energy_total_cost_double_tariff
        device_class: monetary
        icon: mdi:cash-100
        unit_of_measurement: "RUB"
        state: |
          {% set m_day = states("sensor.monthly_energy_day") | float %}
          {% set m_night = states("sensor.monthly_energy_night") | float %}
          {{ (m_day * (states("number.energy_day_tariff") | float) + (m_night * states("number.energy_night_tariff") | float) ) | round(2) }}

utility_meter:
  daily_energy:
    source: sensor.house_total_energy
    name: Daily Energy
    cycle: daily
    tariffs:
      - day
      - night
  monthly_energy:
    source: sensor.house_total_energy
    name: Monthly Energy
    cycle: monthly
    tariffs:
      - day
      - night

automation:
  - alias: Set utility meter tariff
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        at: "07:00:00"
      - platform: time
        at: "23:00:00"
    action:
      choose:
        - alias: energy_tariff_set_night
          conditions: "{{ now().hour < 7 or now().hour >= 23 }}"
          sequence:
            - service: select.select_option
              target:
                entity_id: select.daily_energy
              data:
                option: night
            - service: select.select_option
              target:
                entity_id: select.monthly_energy
              data:
                option: night
        - alias: energy_tariff_set_day
          conditions: "{{ now().hour >= 7 and now().hour < 23 }}"
          sequence:
            - service: select.select_option
              target:
                entity_id: select.daily_energy
              data:
                option: day
            - service: select.select_option
              target:
                entity_id: select.monthly_energy
              data:
                option: day
