# Utility meter
# https://www.home-assistant.io/integrations/utility_meter

utility_meter:
  daily_energy:
    source: sensor.house_total_energy
    name: Daily Energy
    cycle: daily
    tariffs:
      - h1_day
      - h1_night
      - h2_day
      - h2_night
  monthly_energy:
    source: sensor.house_total_energy
    name: Monthly Energy
    cycle: monthly
    tariffs:
      - h1_day
      - h1_night
      - h2_day
      - h2_night

automation:
  - alias: Set utility meter tariff
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        at: "07:00:00"
      - platform: time
        at: "23:00:00"
    action:
        choose:
        - conditions: "{{ now().month < 7 and (now().hour < 7 or now().hour >= 23 ) }}"
          sequence:
            - service: utility_meter.select_tariff
              entity_id: utility_meter.daily_energy
              data:
                tariff: h1_night
            - service: utility_meter.select_tariff
              entity_id: utility_meter.monthly_energy
              data:
                tariff: h1_night
        - conditions: "{{ now().month < 7 and (now().hour >= 7 and now().hour < 23 ) }}"
          sequence:
            - service: utility_meter.select_tariff
              entity_id: utility_meter.daily_energy
              data:
                tariff: h1_day
            - service: utility_meter.select_tariff
              entity_id: utility_meter.monthly_energy
              data:
                tariff: h1_day
        - conditions: "{{ now().month >= 7 and (now().hour < 7 or now().hour >= 23 ) }}"
          sequence:
            - service: utility_meter.select_tariff
              entity_id: utility_meter.daily_energy
              data:
                tariff: h2_night
            - service: utility_meter.select_tariff
              entity_id: utility_meter.monthly_energy
              data:
                tariff: h2_night
        - conditions: "{{ now().month >= 7 and (now().hour >= 7 and now().hour < 23 ) }}"
          sequence:
            - service: utility_meter.select_tariff
              entity_id: utility_meter.daily_energy
              data:
                tariff: h2_day
            - service: utility_meter.select_tariff
              entity_id: utility_meter.monthly_energy
              data:
                tariff: h2_day

# Rub per KW/H
# I полугодие / II полугодие
# Day 3,66 / 3,80
# Night 1,37 / 1,44

sensor:
  - platform: template
    sensors:
      current_energy_cost:
        friendly_name: "cost of kWh for current tariff"
        unit_of_measurement: 'RUB/kWh'
        value_template: |
          {% if is_state("utility_meter.daily_energy", "h1_day") -%}
            3.66
          {% elif is_state("utility_meter.daily_energy", "h2_day") -%}
            3.80
          {% elif is_state("utility_meter.daily_energy", "h1_night") -%}
            1.37
          {% elif is_state("utility_meter.daily_energy", "h2_night") -%}
            1.44
          {%- endif %}
