homeassistant:
  # Home Assistant Instance Name
  name: !secret name

  # Latitude of your location required to calculate the time the sun rises and sets.
  latitude: !secret latitude_home

  # Longitude of your location required to calculate the time the sun rises and sets.
  longitude: !secret longitude_home

  # Altitude above sea level in meters. Impacts weather/sunrise data.
  elevation: !secret elevation
  
  # Units
  unit_system: metric
  temperature_unit: C

  # Timezone
  time_zone: !secret timezone

  # Currency
  currency: !secret currency

  # The URL that Home Assistant is available on from the internet
  external_url: !secret external_url

  # The URL that Home Assistant is available on from your local network
  internal_url: !secret internal_url

  # Customize individual entities
  # customize: !include_dir_merge_named ../customizations/entities

  # Custimize all entities in a domain
  # customize_domain: !include_dir_merge_named ../customizations/domains

  # Custimize entities based on a matching pattern
  # customize_glob: !include_dir_merge_named ../customizations/globs

  # Load packages
  packages: !include_dir_named integrations
