title: Tablet view
views:
  - !include lovelace/tablet/300_home.yaml
  # - !include lovelace/tablet/310_espresense.yaml
  - !include lovelace/tablet/330_control.yaml
  - !include lovelace/tablet/340_camera.yaml
