# Коридор

homeassistant:
  customize:
    # Свет
    light.gateway_light_50ec50c4f23d:
      friendly_name: Лампочка mi hub
      icon: mdi:star-circle-outline

    # Сенсоры

    # Датчик освещённости
    sensor.illumination_50ec50c4f23d:
      friendly_name: Датчик освещённости в mi hub
      device_class: illuminance

  customize_glob:
    # Датчик движения
    "*158d000543e101*":
      friendly_name: Коридор движение
    "*motion_corridor*":
      friendly_name: Коридор движение

    "*158d0006c3d86d*":
      friendly_name: Коридор вход движение
    "*motion_illumination_entrance*":
      friendly_name: Коридор вход движение

script:
  wake_corridor_wall_panel:
    sequence:
      - alias: "Wake corridor wall panel"
        service: mqtt.publish
        data:
          topic: wallpanel/corridorwallpanel/command
          payload: "{\"wake\": true}"

# sensors
sensor:
  # mqtt sensors
  - platform: mqtt
    name: last_event_motion_corridor_occupancy
    device_class: timestamp
    state_topic: "events/date_time/motion_corridor_occupancy/on"
  - platform: mqtt
    name: last_event_motion_illumination_entrance_occupancy
    device_class: timestamp
    state_topic: "events/date_time/motion_illumination_entrance_occupancy/on"

automation:
  - id: corridor_turn_on_tablet_on_motion
    alias: corridor_turn_on_tablet_on_motion
    description: "turn on tablet screen on motion"
    trigger:
      platform: state
      entity_id: binary_sensor.motion_illumination_entrance_occupancy
      to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.main_control
        state: "on"
    action:
      - service: script.wake_corridor_wall_panel

  - id: corridor_rgb_led_strip_on_motion
    alias: corridor_rgb_led_strip_on_motion
    description: "turn on the rgb led strip in coridor for short time on motion"
    trigger:
      platform: state
      entity_id: binary_sensor.motion_illumination_entrance_occupancy
      from: "off"
      to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.light_control
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: select.corridor_rgb_led
            state: "Warning"
          - condition: state
            entity_id: select.corridor_rgb_led
            state: "Alarm"
    action:
      - service: select.select_option
        data:
          option: "Temperature"
        target:
          entity_id: select.corridor_rgb_led
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.motion_illumination_entrance_occupancy
            from: "on"
            to: "off"
      - service: select.select_option
        data:
          option: "Off"
        target:
          entity_id: select.corridor_rgb_led
    mode: restart
