# Коридор

homeassistant:
  customize:
    # Свет
    light.corridor_hub_xiaomi_light:
      friendly_name: Лампочка mi hub
      icon: mdi:star-circle-outline

    # Сенсоры

    # Датчик освещённости
    sensor.corridor_hub_xiaomi_illumination:
      friendly_name: Датчик освещённости в mi hub
      device_class: illuminance

  customize_glob:
    # Датчик движения
    "*158d000543e101*":
      friendly_name: Коридор движение
    "*corridor_motion_bathroom*":
      friendly_name: Коридор движение

    "*158d0006c3d86d*":
      friendly_name: Коридор вход движение
    "*corridor_motion_entrance*":
      friendly_name: Коридор вход движение

script:
  wake_corridor_wall_panel:
    sequence:
      - alias: "Wake corridor wall panel"
        action: mqtt.publish
        data:
          topic: home/corridor/wallpanel/command
          payload: '{"wake": true}'
          retain: false
template:
  - binary_sensor:
      - name: wake_corridor_wall_panel
        state: >
          {{ is_state('binary_sensor.corridor_motion_entrance_occupancy', 'on') or
            states('sensor.entrance_button_doorbell_action') not in
              ['unknown', 'unavailable', 'None'] }}

# sensors
mqtt:
  sensor:
    # mqtt sensors
    - name: corridor_events_motion_bathroom
      device_class: timestamp
      state_topic: "home/corridor/events/motion/corridor_motion_bathroom_occupancy/on"
    - name: corridor_events_motion_entrance
      device_class: timestamp
      state_topic: "home/corridor/events/motion/corridor_motion_entrance_occupancy/on"
    - name: last_event_svetlana_motion_occupancy
      device_class: timestamp
      state_topic: "home/svetlana/svetlana_motion_occupancy/on"

automation:
  - id: corridor_turn_on_tablet_on_motion
    alias: corridor_turn_on_tablet_on_motion
    description: "turn on tablet screen on motion"
    trigger:
      platform: state
      entity_id: binary_sensor.wake_corridor_wall_panel
      to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.main_control
        state: "on"
    action:
      - action: script.wake_corridor_wall_panel

  - id: corridor_rgb_led_strip_on_motion
    alias: corridor_rgb_led_strip_on_motion
    description: "turn on the rgb led strip in coridor for short time on motion"
    trigger:
      - platform: state
        entity_id: binary_sensor.corridor_motion_entrance_occupancy
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.main_control
        state: "on"
    action:
      - alias: "Select Temperature effect on motion"
        action: switch.turn_on
        target:
          entity_id: switch.need_to_show_temperature
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.corridor_motion_entrance_occupancy
            from: "on"
            to: "off"
      - action: switch.turn_off
        target:
          entity_id: switch.need_to_show_temperature
    mode: restart
