binary_sensor:
  # time of day
  - platform: tod
    name: night
    after: '23:00'
    before: '07:00'
    
  - platform: tod
    name: morning
    after: '07:00'
    before: '09:00'
    
  - platform: tod
    name: day
    after: '09:00'
    before: '19:00'
    
  - platform: tod
    name: evening
    after: '19:00'
    before: '23:00'

sensor:
  # date/time
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'time_date'
  - platform: template
    sensors:
      greeting:
        friendly_name: "Greeting"
        value_template: >
          {{iif(is_state("binary_sensor.morning", "on"), "Доброе утро",
              iif(is_state("binary_sensor.day", "on"), "Добрый день",
                iif(is_state("binary_sensor.evening", "on"), "Добрый вечер",
                  "Доброй ночи")))}}
