sensor:
  # date/time
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "time_date"

template:
  - sensor:
      - default_entity_id: sensor.greeting
        name: Greeting
        state: >-
          {{iif(is_state("binary_sensor.morning", "on"), "Доброе утро",
            iif(is_state("binary_sensor.day", "on"), "Добрый день",
              iif(is_state("binary_sensor.evening", "on"),
                "Добрый вечер",
                  "Доброй ночи")))}}"
