# Notification/Warning/Alarm
mqtt:
  binary_sensor:
    - name: is_notification
      state_topic: "home/system/notification/on"
      payload_on: "true"
      payload_off: "false"
    - name: is_warning
      state_topic: "home/system/warning/on"
      payload_on: "true"
      payload_off: "false"
    - name: is_alarm
      state_topic: "home/system/alarm/on"
      payload_on: "true"
      payload_off: "false"
  button:
    - unique_id: cancel_all
      name: "Cancel all"
      command_topic: "home/system/cancel_all"

script:
  generate_notification:
    use_blueprint:
      path: yuri-vashchenko/generate_event.yaml
      input:
        event_severity: "notification"
        value: "true"
  generate_warning:
    use_blueprint:
      path: yuri-vashchenko/generate_event.yaml
      input:
        event_severity: "warning"
        value: "true"
  generate_alarm:
    use_blueprint:
      path: yuri-vashchenko/generate_event.yaml
      input:
        event_severity: "alarm"
        value: "true"
  cancel_notification:
    use_blueprint:
      path: yuri-vashchenko/generate_event.yaml
      input:
        event_severity: "notification"
        value: "false"
  cancel_warning:
    use_blueprint:
      path: yuri-vashchenko/generate_event.yaml
      input:
        event_severity: "warning"
        value: "false"
  cancel_alarm:
    use_blueprint:
      path: yuri-vashchenko/generate_event.yaml
      input:
        event_severity: "alarm"
        value: "false"
  cancel_all:
    sequence:
      - alias: "Cancel notification"
        service: script.turn_on
        target:
          entity_id: script.cancel_notification
      - alias: "Cancel warning"
        service: script.turn_on
        target:
          entity_id: script.cancel_warning
      - alias: "Cancel alarm"
        service: script.turn_on
        target:
          entity_id: script.cancel_alarm
    mode: queued
    max: 100

automation:
  - id: cancel_all_on_button_press
    alias: cancell all on button press
    trigger:
      platform: mqtt
      topic: home/system/cancel_all
      payload: PRESS
    condition:
      - alias: "control mode"
        condition: state
        entity_id: binary_sensor.main_control
        state: "on"
    action:
      alias: "Cancell all alarms, notifications and warnings"
      service: script.cancel_all
