# greetings

script:
  greet:
    variables:
      person:
      target:
      greeting: >
        {{ states("sensor.greeting")}}, {{person}}! Как я рада тебя видеть!
    sequence:
      - service: mqtt.publish
        data_template:
          topic: "home/system/announcement/yandex"
          retain: false
          payload_template: >
            {"message": "{{greeting}}", "target": "{{target or "media_player.yandex_station_mk0000000000000856020000ea9f455c"}}", "volume": "60"}

automation:
  - id: "Greet whoever enters the kitchen"
    alias: "Greet whoever enters the kitchen"
    description: "Greet whoever enters the kitchen"
    trigger:
      - platform: state
        entity_id: sensor.elena_mi_smart_band_6
        from:
        to: "kitchen"
        id: "elena"
      - platform: state
        entity_id: sensor.mama_mi_smart_band_4
        from:
        to: "kitchen"
        id: "mama"
      - platform: state
        entity_id: sensor.michael_mi_smart_band_5
        from:
        to: "kitchen"
        id: "michael"
      - platform: state
        entity_id: sensor.papa_mi_smart_band_4
        from:
        to: "kitchen"
        id: "papa"
      - platform: state
        entity_id: sensor.svetlana_mi_smart_band_6
        from:
        to: "kitchen"
        id: "svetlana"
      - platform: state
        entity_id: sensor.yuri_mi_smart_band_6_nfc
        from:
        to: "kitchen"
        id: "yuri"
    condition:
      - alias: "sound controller"
        condition: state
        entity_id: binary_sensor.sound_control
        state: "on"
    action:
      - alias: "choose who enters"
        choose:
          - conditions:
              condition: trigger
              id: "elena"
            sequence:
              - service: script.greet
                data:
                  person: "Елена"
          - conditions:
              condition: trigger
              id: "mama"
            sequence:
              - service: script.greet
                data:
                  person: "Галина"
          - conditions:
              condition: trigger
              id: "papa"
            sequence:
              - service: script.greet
                data:
                  person: "Алексей"
          - conditions:
              condition: trigger
              id: "svetlana"
            sequence:
              - service: script.greet
                data:
                  person: "Светлана"
          - conditions:
              condition: trigger
              id: "michael"
            sequence:
              - service: script.greet
                data:
                  person: "Михаил"
          - conditions:
              condition: trigger
              id: "yuri"
            sequence:
              - service: script.greet
                data:
                  person: "Юрий"
