# mqtt_room
# https://www.home-assistant.io/integrations/mqtt_room/

sensor:
# One entry for each beacon you want to track
  - platform: mqtt_room
    device_id: "mifit:c668ef8ec6d3"
    name: 'Yuri Mi Smart Band 6 NFC'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120 # number of seconds after which the enitity will get status not_home
  - platform: mqtt_room
    device_id: "mifit:f2542ae6f8bd"
    name: 'Elena Mi Smart Band 6'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120 # number of seconds after which the enitity will get status not_home
  - platform: mqtt_room
    device_id: "mifit:d0f6b95351c7"
    name: 'Papa Mi Smart Band 4'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120 # number of seconds after which the enitity will get status not_home
  - platform: mqtt_room
    device_id: "mifit:d3ccfa54baeb"
    name: 'Mama Mi Smart Band 4'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120 # number of seconds after which the enitity will get status not_home
  - platform: mqtt_room
    device_id: "mifit:f68545ddbad0"
    name: 'Svetlana Mi Smart Band 6'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120 # number of seconds after which the enitity will get status not_home
  - platform: mqtt_room
    device_id: "mifit:c0090a1b2e09"
    name: 'Michael Mi Smart Band 5'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120 # number of seconds after which the enitity will get status not_home
