homeassistant:
  customize:
    sensor.total_automations:
      friendly_name: Автоматизаций в системе
    sensor.total_automations_on:
      friendly_name: Активных автоматизаций
    sensor.total_automations_off:
      friendly_name: Отключенных автоматизаций
    sensor.total_automations_unavailable:
      friendly_name: Недоступных автоматизаций
    sensor.total_scripts:
      friendly_name: Скриптов в системе
    sensor.total_scripts_on:
      friendly_name: Активных скриптов
    sensor.total_scripts_off:
      friendly_name: Отключенных скриптов
    sensor.total_scripts_unavailable:
      friendly_name: Недоступных скриптов
    sensor.total_components:
      friendly_name: Компонентов в системе
    sensor.total_components_updates:
      friendly_name: Доступно обновлений
    sensor.total_lights:
      friendly_name: Светильников в системе
    sensor.total_lights_on:
      friendly_name: Активных светильников
    sensor.total_lights_off:
      friendly_name: Отключенных светильников
    sensor.total_lights_unavailable:
      friendly_name: Недоступных светильников
    sensor.total_switches:
      friendly_name: Реле в системе
    sensor.total_switches_on:
      friendly_name: Активных реле
    sensor.total_switches_off:
      friendly_name: Отключенных реле
    sensor.total_switches_unavailable:
      friendly_name: Недоступных реле
    sensor.total_climates:
      friendly_name: Термостатов в системе
    sensor.total_climates_on:
      friendly_name: Активных Термостатов
    sensor.total_climates_off:
      friendly_name: Отключенных термостатов
    sensor.total_climates_unavailable:
      friendly_name: Недоступных термостатов
    sensor.total_sensors:
      friendly_name: Сенсоров в системе
    sensor.total_sensors_unavailable:
      friendly_name: Недоступных сенсоров
    sensor.total_binary_sensors:
      friendly_name: Бинарных сенсоров в системе
    sensor.total_binary_sensors_unavailable:
      friendly_name: Недоступных бинарных сенсоров
      sensor.total_cameras:
        friendly_name: Камер
      sensor.total_cameras_unavailable:
        friendly_name: Недоступных камер
template:
  - sensor:
      ################# Автоматизации #################

      - name: total_automations
        state: "{{ states.automation | list | count }}"
        icon: mdi:head

      - name: total_automations_on
        state: "{{ states.automation | selectattr('state', 'equalto', 'on') | list | count }}"
        icon: mdi:head-check

      - name: total_automations_off
        state: "{{ states.automation | selectattr('state', 'equalto', 'off') | list | count }}"
        icon: mdi:head-remove

      - name: total_automations_unavailable
        state: "{{ states.automation | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | count }}"
        icon: mdi:head-question

      ################# Скрипты #################

      - name: total_scripts
        state: "{{ states.script | list | count }}"
        icon: mdi:file

      - name: total_scripts_on
        state: "{{ states.script | selectattr('state', 'equalto', 'on') | list | count }}"
        icon: mdi:file-check

      - name: total_scripts_off
        state: "{{ states.script | selectattr('state', 'equalto', 'off') | list | count }}"
        icon: mdi:file-remove

      - name: total_scripts_unavailable
        state: "{{ states.script | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | count }}"
        icon: mdi:file-question

      ################# Обновления #################

      - name: total_components
        state: "{{ states.update | list | count }}"
        icon: mdi:monitor-dashboard

      - name: total_components_updates
        state: "{{ states.update | selectattr('state', 'equalto', 'on') | list | count }}"
        icon: mdi:monitor-arrow-down-variant

      ################# Светильники #################

      - name: total_lights
        state: "{{ states.light | list | count }}"
        icon: mdi:lightbulb-group

      - name: total_lights_on
        state: "{{ states.light | selectattr('state', 'equalto', 'on') | list | count }}"
        icon: mdi:lightbulb-on

      - name: total_lights_off
        state: "{{ states.light | selectattr('state', 'equalto', 'off') | list | count }}"
        icon: mdi:lightbulb

      - name: total_lights_unavailable
        state: "{{ states.light | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | count }}"
        icon: mdi:lightbulb-question

      ################# Реле #################

      - name: total_switches
        state: "{{ states.switch | list | count }}"
        icon: mdi:power

      - name: total_switches_on
        state: "{{ states.switch | selectattr('state', 'equalto', 'on') | list | count }}"
        icon: mdi:power-plug

      - name: total_switches_off
        state: "{{ states.switch | selectattr('state', 'equalto', 'off') | list | count }}"
        icon: mdi:power-plug-off

      - name: total_switches_unavailable
        state: "{{ states.switch | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | count }}"
        icon: mdi:power-plug-outline

      ################# Термостаты #################

      - name: total_climates
        state: "{{ states.climate | list | count }}"
        icon: mdi:thermostat

      - name: total_climates_on
        state: "{{ states.climate | selectattr('state', 'in', ['on', 'heat', 'cool', 'dry']) | list | count }}"
        icon: mdi:thermometer-plus

      - name: total_climates_off
        state: "{{ states.climate | selectattr('state', 'equalto', 'off') | list | count }}"
        icon: mdi:thermometer-minus

      - name: total_climates_unavailable
        state: "{{ states.climate | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | count }}"
        icon: mdi:thermometer-alert

      ################# Сенсоры #################

      - name: total_sensors
        state: "{{ states.sensor | list | count }}"
        icon: mdi:eye

      - name: total_sensors_unavailable
        state: "{{ states.sensor | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | count }}"
        icon: mdi:eye-off

      ################# Бинарные сенсоры #################

      - name: total_binary_sensors
        state: "{{ states.binary_sensor | list | count }}"
        icon: mdi:numeric-10-circle

      - name: total_binary_sensors_unavailable
        state: "{{ states.binary_sensor | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | count }}"
        icon: mdi:alert-circle

      ################# Камеры #################

      - name: total_cameras
        state: "{{ states.camera | list | count }}"
        icon: mdi:cctv

      - name: total_cameras_unavailable
        state: "{{ states.camera | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | count }}"
        icon: mdi:alert-circle
