homeassistant:
  # Allow access to /media to let telegram to send files
  allowlist_external_dirs:
    - "/media"

automation:
  - id: automation id
    alias: automation alias (name)
    trigger:
      - trigger: mqtt
        topic: "home/system/announcement/all"
    condition:
      - alias: "main controller"
        condition: state
        entity_id: input_boolean.main_control
        state: "on"
    action:
      - alias: Send message to telegram
        action: notify.send_message
        data:
          message: "{{ trigger.payload_json['message'] or '' }}"
          entity_id: notify.telegram_bot_1092482274_4189636841
