# Domofon

script:
  domofon_turn_sound_off_at_night:
    alias: Turn domofon sound on or off according of night mode
    sequence:
      - alias: "Chose action depending on night mode"
        choose:
          - conditions:
              - alias: "Night"
                condition: state
                entity_id: binary_sensor.night
                state: "on"
            sequence:
              - alias: "Turn domofon sound off"
                action: switch.turn_off
                target:
                  entity_id: switch.domofon_sound
          - conditions:
              - alias: "Day"
                condition: state
                entity_id: binary_sensor.night
                state: "off"
            sequence:
              - alias: "Turn domofon sound on"
                action: switch.turn_on
                target:
                  entity_id: switch.domofon_sound

automation:
  - id: domofon_turn_off_sound_at_night
    alias: Turn off domofon sound at night
    trigger:
      - platform: state
        entity_id: binary_sensor.night
        from: "off"
        to: "on"
      - platform: state
        entity_id: binary_sensor.night
        from: "on"
        to: "off"
      - platform: event
        event_type:
          - automation_reloaded
          - homeassistant_started
    condition:
      - alias: "Control mode"
        condition: state
        entity_id: binary_sensor.main_control
        state: "on"
    action:
      - alias: "turn domofon sound on or off"
        action: script.turn_on
        target:
          entity_id: script.domofon_turn_sound_off_at_night
