# Прихожая

homeassistant:
  customize_glob:
    # Датчики

    # Входная двевь
    "*158d000544a1a2*":
      friendly_name: Входная дверь

    "sensor.*entrance_door*":
      friendly_name: Входная дверь
    "binary_sensor.*entrance_door*":
      friendly_name: Входная дверь

    # Выключатели, кнопки

    # Звонок
    "*158d00041d99a1*":
      friendly_name: Кнопка звонка

script:
  entrance_door_opened:
    alias: Прихожая - входная дверь открыта слишком долго
    description: Входная дверь открыта слишком долго
    use_blueprint:
      path: "yuri-vashchenko/event_action.yaml"
      input:
        event_severity: "warning"
        event_type: "entrance_door"
        event_id: "opened"
        ringtone_id: "29"
        ringtone_volume: "70"
        announcement_message: Внимание! Входная дверь открыта
        wait_entity: binary_sensor.entrance_door_contact
        wait_entity_state: "off"
        delay_between_repeats: 60
        max_repeats: 10
        announcement_message_end: Входная дверь закрыта

automation:
  - id: entrance_light_on_motion
    alias: Прихожая - включить свет по движению
    initial_state: true
    use_blueprint:
      path: kevinxw/state_based_entity_control.yaml
      input:
        trigger_entity: binary_sensor.entrance_motion_occupancy
        target_entity: switch.entrance_switch_light
        blocker_entity: binary_sensor.light_control
        blocker_entity_state: "off"
        trigger_timeout: 60

  - id: entrance_door_opened_for_too_long
    alias: Прихожая - входная дверь открыта слишком долго
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.entrance_door_contact
        to: "on"
        for:
          seconds: "{{ states('number.entrance_door_warning_open_duration') | int(120)}}"
    condition:
      - condition: state
        entity_id: binary_sensor.main_control
        state: "on"
    action:
      service: script.entrance_door_opened
    mode: single
