# Прихожая

homeassistant:
  customize_glob:
    # Датчики

    # Входная двевь
    "*158d000544a1a2*":
      friendly_name: Входная дверь

    "*door_entrance*":
      friendly_name: Входная дверь

    # Выключатели, кнопки

    # Звонок
    "*158d00041d99a1*":
      friendly_name: Кнопка звонка

automation:
  - id: Entrance_light_on_motion
    alias: Entrance_light_on_motion
    initial_state: true
    use_blueprint:
      path: kevinxw/state_based_entity_control.yaml
      input:
        trigger_entity: binary_sensor.motion_entrance_occupancy
        target_entity: switch.switch_entrance
        blocker_entity: binary_sensor.light_control
        blocker_entity_state: "off"
        trigger_timeout: 60

  - id: entrance_door_opened_for_too_long
    alias: entrance_door_opened_for_too_long
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.door_entrance_contact
        to: "on"
        for:
          seconds: "{{states('number.entrance_door_warning_open_duration') | int}}"
    condition:
      - condition: state
        entity_id: binary_sensor.main_control
        state: "on"
    action:
      - alias: "Publish Warning"
        service: mqtt.publish
        data:
          topic: "warning/entrance_door_opened"
          payload: "on"
          retain: false
      - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.door_entrance_contact
          to: "off"
      - alias: "Publish Warning"
        service: mqtt.publish
        data:
          topic: "warning/entrance_door_opened"
          payload: "off"
          retain: false
    mode: restart

  - id: Announce_opened_entrance_door
    alias: Announce_opened_entrance_door
    initial_state: true
    trigger:
      - platform: mqtt
        topic: "warning/entrance_door_opened"
    variables:
      message: >-
        {% if (trigger.payload == 'on') %}
          "Внимание! Входная дверь открыта!"
        {% elif (trigger.payload == 'off') %}
          "Входная дверь закрыта"
        {% endif %}
    condition:
      condition: state
      entity_id: binary_sensor.sound_control
      state: "on"
    action:
      - alias: "announce opened / closed door"
        service: script.all_say
        data_template:
          message: "{{ message }}"
          volume: 0.8
