input_boolean:
  yuri_at_home:
    name: Yuri at home
    icon: mdi:home

input_number:
  yuri_room_distance:
    name: Yuri room distance
    min: 0
    max: 999.99
    icon: mdi:distance

input_text:
  yuri_room:
    name: Yuri

template:
  - sensor:
      - name: yuri_location
        state: "{{ states('input_text.yuri_room') }}"

automation:
  - id: Set Yuri room based on ESPresence
    alias: Sets room which Yuri is in based on ESPresence
    trigger:
      - id: yuri_watch_ble
        platform: state
        entity_id: sensor.room_yuri_watch_ble
        not_to: not_home
      - id: yuri_phone_ble
        platform: state
        entity_id: sensor.room_yuri_phone_ble
        not_to: not_home
      - id: not_home
        platform: state
        entity_id: sensor.room_yuri_watch_ble
        to: not_home
      - id: not_home
        platform: state
        entity_id: sensor.room_yuri_phone_ble
        to: not_home
    condition:
      - alias: Main control
        condition: state
        entity_id: binary_sensor.main_control
        state: "on"
    action:
      - alias: "Choose by trigger id"
        choose:
          - conditions:
              - alias: "trigger"
                condition: trigger
                id: yuri_watch_ble
              - alias: "Yuri watch_ble not not_home"
                condition: not
                conditions:
                  - condition: state
                    entity_id: sensor.room_yuri_watch_ble
                    state: "not_home"
            sequence:
              - alias: "Set Yuri room"
                service: input_text.set_value
                target:
                  entity_id: input_text.yuri_room
                data:
                  value: "{{ states('sensor.room_yuri_watch_ble') }}"
              - alias: "Set Yuri room distance"
                service: input_number.set_value
                target:
                  entity_id: input_number.yuri_room_distance
                data:
                  value: "{{ state_attr('sensor.room_yuri_watch_ble', 'distance') }}"
              - alias: "Set Yuri at home"
                service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.yuri_at_home
          - conditions:
              - alias: "Yuri Phone BLE"
                condition: and
                conditions:
                  - alias: "trigger"
                    condition: trigger
                    id: yuri_phone_ble
                  - alias: "Yuri phone ble not not_home"
                    condition: not
                    conditions:
                      - condition: state
                        entity_id: sensor.room_yuri_phone_ble
                        state: "not_home"
            sequence:
              - alias: "Set Yuri room"
                service: input_text.set_value
                target:
                  entity_id: input_text.yuri_room
                data:
                  value: "{{ states('sensor.room_yuri_phone_ble') }}"
              - alias: "Set Yuri room distance"
                service: input_number.set_value
                target:
                  entity_id: input_number.yuri_room_distance
                data:
                  value: "{{ state_attr('sensor.room_yuri_phone_ble', 'distance') }}"
              - alias: "Set Yuri at home"
                service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.yuri_at_home
          - conditions:
              - alias: "trigger"
                condition: trigger
                id: not_home
              - alias: "Yuri bubble mini"
                condition: state
                entity_id: sensor.room_yuri_watch_ble
                state: "not_home"
              - alias: "Yuri Phone BLE"
                condition: state
                entity_id: sensor.room_yuri_phone_ble
                state: "not_home"
            sequence:
              - alias: "Set Yuri room"
                service: input_text.set_value
                target:
                  entity_id: input_text.yuri_room
                data:
                  value: "not_home"
              - alias: "Set Yuri room distance"
                service: input_number.set_value
                target:
                  entity_id: input_number.yuri_room_distance
                data:
                  value: NaN
              - alias: "Set Yuri at home"
                service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.yuri_at_home
    mode: queued
