blueprint:
  name: Control air conditioner
  source_url: https://gist.github.com/yuri-vashchenko/TBD
  description: "TBD"
  domain: automation
  input:
    climate_entity:
      selector:
        entity:
          domain: climate
    temperature_entity:
      selector:
        entity:
          domain: sensor
    humidity_entity:
      selector:
        entity:
          domain: sensor
    out_temperature_entity:
      selector:
        entity:
          domain: sensor
    cold_threshold:
      selector:
        entity:
          domain: input_number
    hot_threshold:
      selector:
        entity:
          domain: input_number
    humid_threshold:
      selector:
        entity:
          domain: input_number
    warm_diff:
      selector:
        entity:
          domain: input_number
    windows_entity:
      selector:
        entity:
          domain: binary_sensor
    window_open_duration:
      selector:
        entity:
          domain: input_number
    cool_hvac_mode:
      selector:
        entity:
          domain: input_text
    cool_target_temperature:
      selector:
        entity:
          domain: input_number
    heat_hvac_mode:
      selector:
        entity:
          domain: input_text
    heat_target_temperature:
      selector:
        entity:
          domain: input_number
    dry_hvac_mode:
      selector:
        entity:
          domain: input_text
    dry_target_temperature:
      selector:
        entity:
          domain: input_number
    enabling_entity:
      name: (Optional) Enabling entity
      description: If this entity's state is set to enable entity state (see below)
        automation will trigger. This may be used to make automation triggering based
        on other entity state
      default:
      selector:
        entity: {}
    enabling_entity_state:
      name: (Optional) Enabling entity state
      description: If enabling entity is in this state the automation will trigger
      default: 'on'
      selector:
        entity:
          domain: input_text
trigger_variables:
  _window_open_duration: !input window_open_duration
  window_open_duration: >
    {{ _window_open_duration | default(60) }}

trigger:
  - platform: homeassistant
    event: start
    id: started
  - platform: event
    event_type: automation_reloaded
    id: started
  - platform: state
    entity_id: !input windows_entity
    to: "on"
    for:
      seconds: "{{ window_open_duration }} "
    id: window_opened
  - platform: state
    entity_id: !input windows_entity
    to: "off"
    id: window_closed
  - platform: state
    entity_id: !input temperature_entity
    not_to:
      - unknown
      - unavailable
    id: temperature
  - platform: state
    entity_id: !input humidity_entity
    not_to:
      - unknown
      - unavailable
    id: humidity
condition:
  - alias: "climate control is on"
    condition: state
    entity_id: binary_sensor.climate_control
    state: "on"
variables:
  climate_entity: !input climate_entity
  temperature_entity: !input temperature_entity
  humidity_entity: !input humidity_entity
  out_temperature_entity: !input out_temperature_entity
  windows_entity: !input windows_entity

  __cold_threshold: !input cold_threshold
  _cold_threshold: >
    {{ __cold_threshold | default(22.0) }}
  cold_threshold: >
    {{ _cold_threshold if is_number(_cold_threshold) else states(_cold_threshold) | float(22.0) }}

  __hot_threshold: !input hot_threshold
  _hot_threshold: >
    {{ __hot_threshold | default(28.0) }}
  hot_threshold: >
    {{ _hot_threshold if is_number(_hot_threshold) else states(_hot_threshold) | float(22.0) }}

  __humid_threshold: !input humid_threshold
  _humid_threshold: >
    {{ __humid_threshold | default(80.0) }}
  humid_threshold: >
    {{ _humid_threshold if is_number(_humid_threshold) else states(_humid_threshold) | float(22.0) }}

  __warm_diff: !input warm_diff
  _warm_diff: >
    {{ __warm_diff | default(1.0) }}
  warm_diff: >
    {{ _warm_diff if is_number(_warm_diff) else states(_warm_diff) | float(1.0) }}

  __cool_target_temperature: !input cool_target_temperature
  _cool_target_temperature: >
    {{ __cool_target_temperature | default(16.0) }}
  cool_target_temperature: >
    {{ _cool_target_temperature if is_number(_cool_target_temperature) else states(_cool_target_temperature) | float(16.0) }}

  __dry_target_temperature: !input dry_target_temperature
  _dry_target_temperature: >
    {{ __dry_target_temperature | default(22.0) }}
  dry_target_temperature: >
    {{ _dry_target_temperature if is_number(_dry_target_temperature) else states(_dry_target_temperature) | float(22.0) }}

  __heat_target_temperature: !input heat_target_temperature
  _heat_target_temperature: >
    {{ __heat_target_temperature | default(30.0) }}
  heat_target_temperature: >
    {{ _heat_target_temperature if is_number(_heat_target_temperature) else states(_heat_target_temperature) | float(30.0) }}

  _cool_hvac_mode: !input cool_hvac_mode
  cool_hvac_mode: >
    {{ _cool_hvac_mode or "cool" | trim }}
  _heat_hvac_mode: !input heat_hvac_mode
  heat_hvac_mode: >
    {{ _heat_hvac_mode or "heat" | trim }}
  _dry_hvac_mode: !input dry_hvac_mode
  dry_hvac_mode: >
    {{ _dry_hvac_mode or "dry" | trim }}

  has_in_temp: >
    {{ states(temperature_entity) not in ['unknown', 'unavailable'] }}
  has_in_humidity: >
    {{ states(humidity_entity) not in ['unknown', 'unavailable'] }}
  in_temp: >
    {%- if has_in_temp -%}
      {{ states(temperature_entity) | float }}
    {%- else -%}
      25.0
    {%- endif -%}
  in_humidity: >
    {%- if has_in_humidity -%}
      {{ states(humidity_entity) | float }}
    {%- else -%}
      50.0
    {%- endif -%}
  is_cold: >
    {{ has_in_temp and in_temp < cold_threshold }}
  is_hot: >
    {{ has_in_temp and in_temp > hot_threshold }}
  is_humid: >
    {{ has_in_humidity and in_humidity > humid_threshold }}
  is_warm: "{{ has_in_temp and in_temp > cold_threshold + warm_diff and in_temp < hot_threshold - warm_diff }}"
  is_comfort: "{{ is_warm and not is_humid }}"
  has_out_temp: >
    {{ states(out_temperature_entity) not in
      ['unknown', 'unavailable'] }}
  out_temp: >
    {%- if has_out_temp -%}
      {{ states(out_temperature_entity) | float }}
    {%- else -%}
      25.0
    {%- endif -%}
  windows_state: >
    {{ states(windows_entity) }}
  ac_state: >
    {{ states(climate_entity) }}
  need_off: >
    {{ (windows_state == 'on' or is_comfort ) and ac_state != 'off' }}
  can_heat: >
    {{ has_out_temp and windows_state == 'off' and
      out_temp < 18 and ac_state == 'off' }}
  can_cool: >
    {{ has_out_temp and windows_state == 'off' and
      out_temp > 10 and ac_state == 'off' }}
  can_dry: >
    {{ has_out_temp and windows_state == 'off' and
      out_temp > 10 and ac_state == 'off' }}
action:
  choose:
    - alias: elena_ac_turn_off
      conditions:
        - condition: trigger
          id:
            - started
            - window_opened
            - temperature
            - humidity
        - "{{ need_off }}"
      sequence:
        - alias: "log event"
          service: logbook.log
          data_template:
            name: "turning Elena AC OFF"
            message: >
              Turning AC off on: trigger: {{ trigger.id }}
                climate_entity: {{ climate_entity }},
                temperature_entity: {{ temperature_entity }},
                out_temperature_entity: {{ out_temperature_entity }},
                windows_entity: {{ windows_entity }},
                cold_threshold: {{ cold_threshold }},
                hot_threshold: {{ hot_threshold }},
                humid_threshold: {{ humid_threshold }},
                cool_target_temperature: {{ cool_target_temperature }},
                dry_target_temperature: {{ dry_target_temperature }},
                heat_target_temperature: {{ heat_target_temperature }},
                cool_hvac_mode: {{ cool_hvac_mode }},
                heat_hvac_mode: {{ heat_hvac_mode }},
                dry_hvac_mode: {{ dry_hvac_mode }},
                has_in_temp: {{ has_in_temp }},
                has_in_humidity: {{ has_in_humidity }},
                in_temp: {{ in_temp }},
                in_humidity: {{ in_humidity }},
                is_cold: {{ is_cold }},
                is_hot: {{ is_hot }},
                is_humid: {{ is_humid }},
                is_warm: {{ is_warm }},
                is_comfort: {{ is_comfort }},
                has_out_temp: {{ has_out_temp }},
                out_temp: {{ out_temp }},
                windows_state: {{ windows_state }},
                ac_state: {{ ac_state }},
                need_off: {{ need_off }},
                can_heat: {{ can_heat }},
                can_cool: {{ can_cool }},
                can_dry: {{ can_dry }}
            entity_id: climate.elena_ac
            domain: climate
        - alias: "turn AC off"
          service: climate.turn_off
          target:
            entity_id: "{{ climate_entity }}"
    - alias: elena_ac_heat
      conditions:
        # turn on heating on homeassistant start or automation reloaded if cold
        - condition: trigger
          id:
            - started
            - doors_closed
            - temperature
        - "{{ is_cold and can_heat }}"
      sequence:
        - alias: "log event"
          service: logbook.log
          data_template:
            name: "Turn AC on (heat)"
            message: >
              Turning AC ON (heat) on: trigger: {{ trigger.id }},
                climate_entity: {{ climate_entity }},
                temperature_entity: {{ temperature_entity }},
                out_temperature_entity: {{ out_temperature_entity }},
                windows_entity: {{ windows_entity }},
                cold_threshold: {{ cold_threshold }},
                hot_threshold: {{ hot_threshold }},
                humid_threshold: {{ humid_threshold }},
                cool_target_temperature: {{ cool_target_temperature }},
                dry_target_temperature: {{ dry_target_temperature }},
                heat_target_temperature: {{ heat_target_temperature }},
                cool_hvac_mode: {{ cool_hvac_mode }},
                heat_hvac_mode: {{ heat_hvac_mode }},
                dry_hvac_mode: {{ dry_hvac_mode }},
                has_in_temp: {{ has_in_temp }},
                has_in_humidity: {{ has_in_humidity }},
                in_temp: {{ in_temp }},
                in_humidity: {{ in_humidity }},
                is_cold: {{ is_cold }},
                is_hot: {{ is_hot }},
                is_humid: {{ is_humid }},
                is_warm: {{ is_warm }},
                is_comfort: {{ is_comfort }},
                has_out_temp: {{ has_out_temp }},
                out_temp: {{ out_temp }},
                windows_state: {{ windows_state }},
                ac_state: {{ ac_state }},
                need_off: {{ need_off }},
                can_heat: {{ can_heat }},
                can_cool: {{ can_cool }},
                can_dry: {{ can_dry }}
            entity_id: "{{ climate_entity }}"
            domain: climate
        - alias: "Turn AC on (heat)"
          service: climate.set_temperature
          data:
            entity_id: "{{ climate_entity }}"
            temperature: "{{ heat_target_temperature }}"
            hvac_mode: "{{ heat_hvac_mode }}"
    - alias: elena_ac_cool
      conditions:
        # turn on cooling on homeassistant start or automation reloaded if cold
        - condition: trigger
          id:
            - started
            - doors_closed
            - temperature
        - "{{ is_hot and can_cool }}"
      sequence:
        - alias: "log event"
          service: logbook.log
          data_template:
            name: "Turn AC on (cool)"
            message: >
              Turning AC ON (cool) on: trigger: {{ trigger.id }},
                climate_entity: {{ climate_entity }},
                temperature_entity: {{ temperature_entity }},
                out_temperature_entity: {{ out_temperature_entity }},
                windows_entity: {{ windows_entity }},
                cold_threshold: {{ cold_threshold }},
                hot_threshold: {{ hot_threshold }},
                humid_threshold: {{ humid_threshold }},
                cool_target_temperature: {{ cool_target_temperature }},
                dry_target_temperature: {{ dry_target_temperature }},
                heat_target_temperature: {{ heat_target_temperature }},
                cool_hvac_mode: {{ cool_hvac_mode }},
                heat_hvac_mode: {{ heat_hvac_mode }},
                dry_hvac_mode: {{ dry_hvac_mode }},
                has_in_temp: {{ has_in_temp }},
                has_in_humidity: {{ has_in_humidity }},
                in_temp: {{ in_temp }},
                in_humidity: {{ in_humidity }},
                is_cold: {{ is_cold }},
                is_hot: {{ is_hot }},
                is_humid: {{ is_humid }},
                is_warm: {{ is_warm }},
                is_comfort: {{ is_comfort }},
                has_out_temp: {{ has_out_temp }},
                out_temp: {{ out_temp }},
                windows_state: {{ windows_state }},
                ac_state: {{ ac_state }},
                need_off: {{ need_off }},
                can_heat: {{ can_heat }},
                can_cool: {{ can_cool }},
                can_dry: {{ can_dry }}
            entity_id: climate_entity
            domain: climate
        - alias: "Turn AC on (cool)"
          service: climate.set_temperature
          data:
            entity_id: "{{ climate_entity }}"
            temperature: "{{ cool_target_temperature }}"
            hvac_mode: "{{ cool_hvac_mode }}"
    - alias: elena_ac_dry
      conditions:
        # turn on drying on homeassistant start or automation reloaded if cold
        - condition: trigger
          id:
            - started
            - doors_closed
            - temperature
            - humidity
        - "{{ is_warm and is_humid and can_dry }}"
      sequence:
        - alias: "log event"
          service: logbook.log
          data_template:
            name: "Turn AC on (dry)"
            message: >
              Turning AC ON (dry) on: trigger: {{ trigger.id }},
                climate_entity: {{ climate_entity }},
                temperature_entity: {{ temperature_entity }},
                out_temperature_entity: {{ out_temperature_entity }},
                windows_entity: {{ windows_entity }},
                cold_threshold: {{ cold_threshold }},
                hot_threshold: {{ hot_threshold }},
                humid_threshold: {{ humid_threshold }},
                cool_target_temperature: {{ cool_target_temperature }},
                dry_target_temperature: {{ dry_target_temperature }},
                heat_target_temperature: {{ heat_target_temperature }},
                cool_hvac_mode: {{ cool_hvac_mode }},
                heat_hvac_mode: {{ heat_hvac_mode }},
                dry_hvac_mode: {{ dry_hvac_mode }},
                has_in_temp: {{ has_in_temp }},
                has_in_humidity: {{ has_in_humidity }},
                in_temp: {{ in_temp }},
                in_humidity: {{ in_humidity }},
                is_cold: {{ is_cold }},
                is_hot: {{ is_hot }},
                is_humid: {{ is_humid }},
                is_warm: {{ is_warm }},
                is_comfort: {{ is_comfort }},
                has_out_temp: {{ has_out_temp }},
                out_temp: {{ out_temp }},
                windows_state: {{ windows_state }},
                ac_state: {{ ac_state }},
                need_off: {{ need_off }},
                can_heat: {{ can_heat }},
                can_cool: {{ can_cool }},
                can_dry: {{ can_dry }}
            entity_id: climate.elena_ac
            domain: climate
        - alias: "Turn AC on (dry)"
          service: climate.set_temperature
          data:
            entity_id: "{{ climate_entity }}"
            temperature: "{{ dry_target_temperature }}"
            hvac_mode: "{{ dry_hvac_mode }}"
  default:
    - alias: "log event"
      service: logbook.log
      data_template:
        name: "Turn AC on (dry)"
        message: >
          Doing nothing. Trigger id: {{ trigger.id }},
          climate_entity: {{ climate_entity }},
          temperature_entity: {{ temperature_entity }},
          out_temperature_entity: {{ out_temperature_entity }},
          windows_entity: {{ windows_entity }},
          cold_threshold: {{ cold_threshold }},
          hot_threshold: {{ hot_threshold }},
          humid_threshold: {{ humid_threshold }},
          cool_target_temperature: {{ cool_target_temperature }},
          dry_target_temperature: {{ dry_target_temperature }},
          heat_target_temperature: {{ heat_target_temperature }},
          cool_hvac_mode: {{ cool_hvac_mode }},
          heat_hvac_mode: {{ heat_hvac_mode }},
          dry_hvac_mode: {{ dry_hvac_mode }},
          has_in_temp: {{ has_in_temp }},
          has_in_humidity: {{ has_in_humidity }},
          in_temp: {{ in_temp }},
          in_humidity: {{ in_humidity }},
          is_cold: {{ is_cold }},
          is_hot: {{ is_hot }},
          is_humid: {{ is_humid }},
          is_warm: {{ is_warm }},
          is_comfort: {{ is_comfort }},
          has_out_temp: {{ has_out_temp }},
          out_temp: {{ out_temp }},
          windows_state: {{ windows_state }},
          ac_state: {{ ac_state }},
          need_off: {{ need_off }},
          can_heat: {{ can_heat }},
          can_cool: {{ can_cool }},
          can_dry: {{ can_dry }}
        entity_id: climate.elena_ac
        domain: climate
