# Yandex (alice) say

automation:
  - id: Publish yandex_say when all_say message received
    alias: publish_yandex_say_on_all_say
    initial_state: true
    trigger:
      - platform: mqtt
        topic: "home/system/announcement/all"
    condition:
      - alias: "main controller"
        condition: state
        entity_id: binary_sensor.main_control
        state: "on"
    variables:
      message: >
        {{ trigger.payload_json['message'] or '' }}
      target: >
        {{ trigger.payload_json['yandex_target'] or 'group.alice' }}
      volume: >
        {{ trigger.payload_json['volume'] or "80" }}
    action:
      - alias: "publish yandex_say mqtt message"
        service: mqtt.publish
        data_template:
          topic: "home/system/announcement/yandex"
          retain: false
          payload: >
            {{ "{ \"message\": \"" + message + "\", \"target\": \"" + target + "\", \"volume\": \"" + volume | string + "\" }" }}

  - id: Announce message via yandex_say when received mqtt message
    alias: yandex_say_message_on_mqtt
    initial_state: true
    trigger:
      - platform: mqtt
        topic: "home/system/announcement/yandex"
    condition:
      - alias: "sound controller"
        condition: state
        entity_id: binary_sensor.sound_control
        state: "on"
    variables:
      message: >
        {{ trigger.payload_json['message'] or '' }}
      volume: >
        {{ trigger.payload_json['volume'] or '80' }}
      target: >
        {{ trigger.payload_json['target'] or 'group.alice' }}
    action:
      - service: media_player.play_media
        target:
          entity_id: "{{ target }}"
        data_template:
          media_content_id: "{{ message }}"
          media_content_type: text
          extra:
            volume_level: "{{ (volume | float) / 100.0 }}"
