# Ванная

homeassistant:
  customize_glob:
    "*158d00047f8591*":
      friendly_name: Ванная - датчик протечки воды
  customize:
    binary_sensor.mqtt_bathroom_water_leak:
      friendly_name: Ванная - mqtt датчик протечки воды
mqtt:
  binary_sensor:
    - name: mqtt_bathroom_water_leak
      state_topic: "home/bathroom/water_leak"
      payload_on: "on"
      payload_off: "off"
      device_class: moisture

script:
  bathroom_water_leak_triggered:
    alias: Ванная - сработал датчик протечки воды
    description: "bathroom water leak detector triggered"
    use_blueprint:
      path: "yuri-vashchenko/event_action.yaml"
      input:
        event_severity: "alarm"
        event_type: "bathroom"
        event_id: "water_leak"
        ringtone_id: "2"
        ringtone_volume: "100"
        announcement_message: "Тревога! Обнаружена протечка воды на кухне"
        wait_entity: binary_sensor.mqtt_bathroom_water_leak
        wait_entity_state: "off"
        delay_between_repeats: 60
        max_repeats: 15
        announcement_message_end: "Протечка воды на кухне устранена"

automation:
  - id: bathroom_water_leak_detector_publish_mqtt
    alias: Ванная - Публикация MQTT сообщения при обнаружении протечки воды
    description: "Ванная - Публикация MQTT сообщения при обнаружении протечки воды"
    use_blueprint:
      path: yuri-vashchenko/publish_mqtt_on_entity_state_change.yaml
      input:
        trigger_entity: binary_sensor.bathroom_water_leak_water_leak
        topic: "home/bathroom/water_leak"
        retain: true
        enabling_entity: binary_sensor.main_control
  - id: bathroom_water_leak_detector_alarm
    alias: Ванная - запуск скрипта при срабатывании датчика протечки воды
    description: "Ванная - запуск скрипта при срабатывании датчика протечки воды"
    trigger:
      - platform: state
        entity_id: binary_sensor.mqtt_bathroom_water_leak
        to: "on"
    condition: "{{ is_state('binary_sensor.sound_control', 'on') }}"
    action:
      action: script.bathroom_water_leak_triggered
