# Ванная

recorder:
  include:
    entities:
      - sensor.bathroom_plug_washer_machine_energy
      - sensor.bathroom_plug_washer_machine_power
      - switch.bathroom_plug_washer_machine
      - binary_sensor.bathroom_washer_machine_washing

homeassistant:
  customize:
    # Розетка стиральной машины
    switch.bathroom_plug_washer_machine_power_outage_memory:
      friendly_name: "Ванная: Розетка стиральной машины память отключения"

    switch.bathroom_plug_washer_machine:
      friendly_name: Cтиральная машина, питание
      icon: mdi:power-socket-eu
    sensor.bathroom_plug_washer_machine_power:
      friendly_name: Cтиральная машина, мощность
      unit_of_measurement: Вт
      device_class: power
    sensor.bathroom_plug_washer_machine_energy:
      friendly_name: Cтиральная машина, энергия
      icon: mdi:chart-line

    automation.bathroom_washer_machine_washing_complete:
      friendly_name: Уведомление о завершении стирки
      icon: mdi:washing-machine-alert

template:
  - binary_sensor:
      - name: bathroom_washer_machine_washing
        unique_id: bathroom_washer_machine_washing
        state: >
          {{ states('sensor.bathroom_plug_washer_machine_power') | float(0.0) > 6.0 }}
        delay_on:
          minutes: 2
        delay_off:
          minutes: 2
        device_class: running

script:
  bathroom_washer_machine_washing_start:
    alias: Запись момента начала стирки
    sequence:
      - alias: запись момента начала стирки
        service: mqtt.publish
        data:
          topic: >
            events/date_time/notification/washing_machine/started
          payload: "{{ now() }}"
          retain: true

  bathroom_washer_machine_washing_complete_notification:
    alias: Нотификация по завершению стирки
    description: Ванная - Нотификация по завершению стирки
    use_blueprint:
      path: "yuri-vashchenko/event_action.yaml"
      input:
        event_severity: "notification"
        event_type: "washing_machine"
        event_id: "complete"
        wait_entity: binary_sensor.bathroom_washer_machine_washing
        wait_entity_state: "off"
        ringtone_id: "11"
        announcement_message: "Стирка завершена. Не забудьте повесить бельё сушиться"
        delay_between_repeats: 1
        max_repeats: 1

  bathroom_washer_machine_washing_complete:
    alias: Завершение стирки
    sequence:
      - service: telegram_bot.send_message
        data:
          target: !secret telegram_id_yuri
          message: |
                {{"\U0001F9D9"}} Стирка завершена {{ states('sensor.time_date') }}
      - alias: Не отправлять нотификации ночью
        condition: state
        entity_id: binary_sensor.night
        state: "off"
      - service: script.bathroom_washer_machine_washing_complete_notification

automation:
  - alias: bathroom_washer_machine_washing_complete
    id: bathroom_washer_machine_washing_complete
    description: Уведомление о завершении стирки
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_washer_machine_washing
        from: 'off'
        to: 'on'
        id: washing_started
      - platform: state
        entity_id: binary_sensor.bathroom_washer_machine_washing
        from: 'on'
        to: 'off'
        id: washing_completed
    condition:
      - condition: state
        entity_id: binary_sensor.main_control
        state: 'on'
    action:
      - alias: Запуск или остановка стирки
        choose:
          - conditions:
              condition: trigger
              id: washing_started
            sequence:
              - alias: Запуск скрипта оповещения о начале стирки
                service: script.bathroom_washer_machine_washing_start
          - conditions:
              condition: trigger
              id: washing_completed
            sequence:
              - alias: Запуск скрипта оповещения об окончании стирки
                service: script.bathroom_washer_machine_washing_complete
