homeassistant:
  customize:
    sensor.elena_thermometer_01_temperature:
      friendly_name: Температура в Лениной комнате на часах
    sensor.elena_thermometer_01_humidity:
      friendly_name: Влажность в Лениной комнате на часах
    sensor.elena_thermometer_02_temperature:
      friendly_name: Температура в Лениной комнате у кровати
    sensor.elena_thermometer_02_humidity:
      friendly_name: Влажность в Лениной комнате у кровати
    sensor.elena_room_temperature:
      friendly_name: Температура в Лениной комнате
    sensor.elena_room_humidity:
      friendly_name: Влажность в Лениной комнате

mqtt:
  number:
    # Low temperature threshold for 'cold' condition
    - name: "Холодно, если температура ниже"
      object_id: elena_room_cold_threshold
      icon: "mdi:thermometer-low"
      command_topic: "home/elena/settings/cold_threshold"
      state_topic: "home/elena/settings/cold_threshold"
      min: 10.0
      max: 25.0
      step: 1
      retain: true

    # High temperature threshold for 'hot' condition
    - name: "Жарко, если температура выше"
      object_id: elena_room_hot_threshold
      icon: "mdi:thermometer-high"
      command_topic: "home/elena/settings/hot_threshold"
      state_topic: "home/elena/settings/hot_threshold"
      min: 25.0
      max: 40.0
      step: 1
      retain: true

    # Low humidity threshold for 'dry' condition
    - name: "Сухо, если влажность ниже"
      object_id: elena_room_dry_threshold
      icon: "mdi:water-percent-alert"
      command_topic: "home/elena/settings/dry_threshold"
      state_topic: "home/elena/settings/dry_threshold"
      min: 1.0
      max: 50.0
      step: 1
      retain: true

    # High humidity threshold for 'humid' condition
    - name: "Влажно, если влажность выше"
      object_id: elena_room_humid_threshold
      icon: "mdi:water-percent-alert"
      command_topic: "home/elena/settings/humid_threshold"
      state_topic: "home/elena/settings/humid_threshold"
      min: 50.0
      max: 100.0
      step: 1
      retain: true

template:
  - binary_sensor:
      - unique_id: elena_thermometer_01_available
        state: >
          {{ is_number(states("sensor.elena_thermometer_01_temperature")) and
            is_number(states("sensor.elena_thermometer_01_humidity")) }}
        device_class: connectivity
      - unique_id: elena_thermometer_02_available
        state: >
          {{ is_number(states("sensor.elena_thermometer_02_temperature")) and
            is_number(states("sensor.elena_thermometer_02_humidity")) }}
        device_class: connectivity
      - unique_id: elena_room_is_cold
        state: >
          {{ states("sensor.elena_room_temperature") <
            states("number.elena_room_cold_threshold") }}
        device_class: cold
      - unique_id: elena_room_is_hot
        state: >
          {{ states("sensor.elena_room_temperature") >
            states("number.elena_room_hot_threshold") }}
        device_class: heat
      - unique_id: elena_room_is_humid
        state: >
          {{ states("sensor.elena_room_humidity") >
            states("number.elena_room_humid_threshold") }}
      - unique_id: elena_room_is_dry
        state: >
          {{ states("sensor.elena_room_humidity") <
            states("number.elena_room_dry_threshold") }}
      - unique_id: elena_room_is_temperature_normal
        state: >
          {{ is_state("binary_sensor.elena_room_is_cold", "off") and
            is_state("binary_sensor.elena_room_is_hot", "off") }}
      - unique_id: elena_room_is_humidity_normal
        state: >
          {{ is_state("binary_sensor.elena_room_is_humid", "off") and
            is_state("binary_sensor.elena_room_is_dry", "off") }}
      - unique_id: elena_room_is_climate_normal
        state: >
          {{ is_state("binary_sensor.elena_room_is_temperature_normal", "on") and
            is_state("binary_sensor.elena_room_is_humidity_normal", "on") }}
      - unique_id: elena_ac_control
        state: >
          # don't allow auto AC control on night or when main control is off
          {{ is_state("binary_sensor.main_control", "on") and
            is_state("binary_sensor.night", "off") }}
      - unique_id: elena_doors_windows
        state: >
          # namespace for result
          {% set ns = namespace(state=false) -%}
          # check that all windows on balcony are closed
          {% for window in states.binary_sensor | selectattr('object_id', 'contains', 'balcony_window') | selectattr('object_id', 'contains', 'contact') | map(attribute='state') | list %}
          {% set ns.state = ns.state or (window | bool) %}
          {% endfor %}
          # it is OK if windows opened and balcony door closed or vice versa
          {% set ns.state = ns.state and (states('binary_sensor.balcony_door_elena_contact') | bool) %}
          # it is not OK if room door opened
          {% set ns.state = ns.state or (states('binary_sensor.elena_door_contact') | bool) %}
          {{ ns.state }}

  - sensor:
      - unique_id: elena_room_temperature
        state: >
          {{ (states("sensor.elena_thermometer_01_temperature") | float +
              states("sensor.elena_thermometer_02_temperature") | float) / 2.0
              if is_state("binary_sensor.elena_thermometer_01_available", "on") and
                  is_state("binary_sensor.elena_thermometer_02_available", "on")
              else
                states("sensor.elena_thermometer_01_temperature") | float
              if is_state("binary_sensor.elena_thermometer_01_available", "on")
              else
                states("sensor.elena_thermometer_02_temperature") }}
        state_class: measurement
        device_class: temperature
        unit_of_measurement: °C
      - unique_id: elena_room_humidity
        state: >
          {{ (states("sensor.elena_thermometer_01_humidity") | float +
              states("sensor.elena_thermometer_02_humidity") | float) / 2.0
              if is_state("binary_sensor.elena_thermometer_01_available", "on") and
                  is_state("binary_sensor.elena_thermometer_02_available", "on")
              else
                states("sensor.elena_thermometer_01_humidity") | float
              if is_state("binary_sensor.elena_thermometer_01_available", "on")
              else
                states("sensor.elena_thermometer_02_humidity") }}
        state_class: measurement
        device_class: humidity
        unit_of_measurement: "%"

climate:
  - platform: smartir
    name: elena_ac
    unique_id: elena_ac
    device_code: 1400
    controller_data: remote.elena_remote_broadlink
    temperature_sensor: sensor.elena_room_temperature
    humidity_sensor: sensor.elena_room_humidity
    power_sensor: binary_sensor.elena_ac_power

automation:
  - id: "Elena Air conditioner control"
    alias: "Упревление кондиционером в Лениной комнате"
    description: "Упревление кондиционером в Лениной комнате"
    use_blueprint:
      path: yuri-vashchenko/auto_ac_control.yaml
      input:
        climate_entity: climate.elena_ac
        temperature_entity: sensor.elena_room_temperature
        humidity_entity: sensor.elena_room_humidity
        out_temperature_entity: sensor.street_thermometer_temperature
        cold_threshold: number.elena_room_cold_threshold
        hot_threshold: number.elena_room_hot_threshold
        humid_threshold: number.elena_room_humid_threshold
        warm_diff: 1.0
        windows_entity: binary_sensor.elena_doors_windows
        window_open_duration: number.elena_ac_door_open_duration
        cool_hvac_mode: "cool"
        cool_target_temperature: 16.0
        heat_hvac_mode: "heat"
        heat_target_temperature: 30.0
        dry_hvac_mode: "dry"
        dry_target_temperature: 22.0
        enabling_entity: binary_sensor.elena_ac_control
        enabling_entity_state: "on"
