# Aqara magic cube control

input_number:
  active_face:
    initial: -1
    min: -1
    max: 6

automation:
  - id: elena_cube_yuri_test
    alias: elena_cube_yuri_test
    description: "Cube test"
    use_blueprint:
      path: yuri-vashchenko/aqara_magic_cube.yaml
      input:
        remote: sensor.elena_cube_yuri_action
        active_face: input_number.active_face
        # flip_90: false
        # cube_flip_90: {}
        # flip_180: false
        # cube_flip_180: {}
        # flip_any: false
        # cube_flip_1: {}
        # cube_flip_2: {}
        # cube_flip_3: {}
        # cube_flip_4: {}
        # cube_flip_5: {}
        # cube_flip_6: {}
        # slide_any_side: false
        # cube_slide_any: {}
        # tap_any_side: false
        # cube_tap_any: {}
        one_to_two:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 1 на сторону 2"
        one_to_three:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 1 на сторону 3"
        one_to_four:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 1 на сторону 4"
        one_to_five:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 1 на сторону 5"
        one_to_six:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 1 на сторону 6"
        two_to_one:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 2 на сторону 1"
        two_to_three:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 2 на сторону 3"
        two_to_four:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 2 на сторону 4"
        two_to_five:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 2 на сторону 5"
        two_to_six:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 2 на сторону 6"
        three_to_one:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 3 на сторону 1"
        three_to_two:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 3 на сторону 2"
        three_to_four:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 3 на сторону 4"
        three_to_five:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 3 на сторону 5"
        three_to_six:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 3 на сторону 6"
        four_to_one:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 4 на сторону 1"
        four_to_two:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 4 на сторону 2"
        four_to_three:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 4 на сторону 3"
        four_to_five:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 4 на сторону 5"
        four_to_six:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 4 на сторону 6"
        five_to_one:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 5 на сторону 1"
        five_to_two:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 5 на сторону 2"
        five_to_three:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 5 на сторону 3"
        five_to_four:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 5 на сторону 4"
        five_to_six:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 5 на сторону 6"
        six_to_one:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 6 на сторону 1"
        six_to_two:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 6 на сторону 2"
        six_to_three:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 6 на сторону 4"
        six_to_four:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 6 на сторону 4"
        six_to_five:
          action: script.elena_nest_say
          data:
            message: "поворот со стороны 6 на сторону 5"
        one_to_one:
          action: script.elena_nest_say
          data:
            message: "постучали на стороне 1"
        two_to_two:
          action: script.elena_nest_say
          data:
            message: "постучали на стороне 2"
        three_to_three:
          action: script.elena_nest_say
          data:
            message: "постучали на стороне 3"
        four_to_four:
          action: script.elena_nest_say
          data:
            message: "постучали на стороне 4"
        five_to_five:
          action: script.elena_nest_say
          data:
            message: "постучали на стороне 5"
        six_to_six:
          action: script.elena_nest_say
          data:
            message: "постучали на стороне 6"
        slide_on_one:
          action: script.elena_nest_say
          data:
            message: "подвигали на стороне 1"
        slide_on_two:
          action: script.elena_nest_say
          data:
            message: "подвигали на стороне 2"
        slide_on_three:
          action: script.elena_nest_say
          data:
            message: "подвигали на стороне 3"
        slide_on_four:
          action: script.elena_nest_say
          data:
            message: "подвигали на стороне 4"
        slide_on_five:
          action: script.elena_nest_say
          data:
            message: "подвигали на стороне 5"
        slide_on_six:
          action: script.elena_nest_say
          data:
            message: "подвигали на стороне 6"
        cube_wake:
          action: script.elena_nest_say
          data:
            message: "проснулись"
        cube_drop:
          action: script.elena_nest_say
          data:
            message: "бросили"
        cube_shake:
          action: script.elena_nest_say
          data:
            message: "потрясли"
        # rotate_any_side: false
        # rotate_right: {}
        # rotate_left: {}
        rotate_left_side_1:
          action: script.elena_nest_say
          data:
            message: "поворот влево, сторона 1"
        rotate_left_side_2:
          action: script.elena_nest_say
          data:
            message: "поворот влево, сторона 2"
        rotate_left_side_3:
          action: script.elena_nest_say
          data:
            message: "поворот влево, сторона 3"
        rotate_left_side_4:
          action: script.elena_nest_say
          data:
            message: "поворот влево, сторона 4"
        rotate_left_side_5:
          action: script.elena_nest_say
          data:
            message: "поворот влево, сторона 5"
        rotate_left_side_6:
          action: script.elena_nest_say
          data:
            message: "поворот влево, сторона 6"
        rotate_right_side_1:
          action: script.elena_nest_say
          data:
            message: "поворот вправо, сторона 1"
        rotate_right_side_2:
          action: script.elena_nest_say
          data:
            message: "поворот вправо, сторона 2"
        rotate_right_side_3:
          action: script.elena_nest_say
          data:
            message: "поворот вправо, сторона 3"
        rotate_right_side_4:
          action: script.elena_nest_say
          data:
            message: "поворот вправо, сторона 4"
        rotate_right_side_5:
          action: script.elena_nest_say
          data:
            message: "поворот вправо, сторона 5"
        rotate_right_side_6:
          action: script.elena_nest_say
          data:
            message: "поворот вправо, сторона 6"
