# Ленина комната

homeassistant:
  customize:
    # Розетка кондиционера
    switch.elena_plug_ac_power_outage_memory:
      friendly_name: Розетка кондиционера память отключения

    # Розетка телевизора 65
    switch.elena_plug_tv_power_outage_memory:
      friendly_name: Розетка телевизора 65 память отключения

      # Телевизор
    media_player.tv:
      friendly_name: TV
      device_class: tv

    media_player.yandex_station_u00yg86004sfjk:
      friendly_name: yandex_station_elena

  customize_glob:
    # Кнопки
    "*158d0003d13dca*":
      friendly_name: Лена кнопка
    "*elena_button_elena*":
      friendly_name: Лена кнопка

    "*158d00035846ec*":
      friendly_name: Юра кнопка
    "*button_yuri*":
      friendly_name: Юра кнопка

    "*158d000709b340*":
      friendly_name: Юра куб

    # Розетка кондиционера
    "*158d00032d3a92*":
      friendly_name: Розетка кондиционера
    "*elena_plug_ac*":
      friendly_name: Розетка кондиционера

    # Розетка телевизора
    "*158d0003c77e0c*":
      friendly_name: Розетка телевизора 65
    "*elena_plug_tv*":
      friendly_name: Розетка телевизора 65

    # Датчики
    "*158d000460dde9*":
      friendly_name: Дверь на балкон
    "*door_balcony*":
      friendly_name: Дверь на балкон
      device_class: door

    "*158d000483f52f*":
      friendly_name: Лена дверь
    "*door_elena*":
      friendly_name: Лена дверь
      device_class: door

    "*158d000464d3fc*":
      friendly_name: Лена движение
    "*elena_motion*":
      friendly_name: Лена движение

template:
  - binary_sensor:
      - name: elena_ac_power
        state: >
          {%- if states('sensor.elena_plug_ac_power') not in ['unknown', 'unavailable'] -%}
            {{ states('sensor.elena_plug_ac_power') | float > 50.0 }}
          {%- else -%}
            false
          {%- endif -%}
        device_class: plug
      - name: host_occupancy
        state: >
          {{ states('person.yuri_vashchenko') in ['home', 'Дом'] or
            states('person.elena_vashchenko') in ['home', 'Дом'] }}

  - sensor:
      - name: elena_total_power
        state: >
          {% set ns = namespace(states=[]) -%}
          {% for plug in expand('group.elena_plug') | selectattr('domain','eq','switch') | map(attribute='entity_id') -%}
            {% set energy_sensor_name = plug | replace("switch", "sensor") + "_power" -%}
            {% if is_number(states(energy_sensor_name)) -%}
            {% set plug_energy = states(energy_sensor_name) | float -%}
            {% set ns.states = ns.states + [plug_energy] -%}
            {% endif -%}
          {% endfor -%}
          {{ ns.states | sum | round(2) }}
        state_class: measurement
        unit_of_measurement: "W"
        device_class: power

      - name: elena_total_energy
        state: >
          {% set ns = namespace(states=[]) -%}
          {% for plug in expand('group.elena_plug') | selectattr('domain','eq','switch') | map(attribute='entity_id') -%}
            {% set energy_sensor_name = plug | replace("switch", "sensor") + "_energy" -%}
            {% if is_number(states(energy_sensor_name)) -%}
            {% set plug_energy = states(energy_sensor_name) | float -%}
            {% set ns.states = ns.states + [plug_energy] -%}
            {% endif -%}
          {% endfor -%}
          {{ ns.states | sum | round(2) }}
        state_class: total_increasing
        unit_of_measurement: "kWh"
        device_class: energy

      - name: users_in_elena_room
        state: >
          {{ states.input_text | selectattr('entity_id','contains','room') | selectattr('state','eq','elena') | list | count }}
        attributes:
          users: >
            {{ states.input_text | selectattr('entity_id','contains','room') | selectattr('state','eq','elena') | map(attribute='name') | list }}

script:
  led_strip_toggle:
    alias: led_strip_toggle
    sequence:
      - action: remote.send_command
        data:
          entity_id: remote.elena_remote_broadlink
          device: led_strip
          command: power

  learn_led_strip_toggle:
    sequence:
      - action: remote.learn_command
        data:
          entity_id: remote.elena_remote_broadlink
          device: led_strip
          command: power

  elena_turn_off_tv_light_ac:
    sequence:
      - alias: "Turn off TV"
        action: media_player.turn_off
        target:
          entity_id: media_player.elena_tv
      - alias: "Turn off the light"
        action: light.turn_off
        target:
          entity_id:
            - group.elena_light_yeelight
            - light.elena_tv_wled
      - alias: "Turn off the AC"
        action: climate.turn_off
        target:
          entity_id: climate.elena_ac

  romantic:
    sequence:
      - action: script.led_strip_toggle

scene:
  - name: Movies
    entities:
      light.elena_yeelight_nightlight: "on"
      media_player.tv:
        state: "on"
        source: "КиноПоиск: новинки в FullHD"
  - name: Sport
    entities:
      light.elena_yeelight_nightlight: "on"
      media_player.tv:
        state: "on"
        source: "Eurosport Player"

automation:
  - id: "elena_light_control_button_l"
    alias: "elena_light_control_button_l"
    description: "Control Yeelight 650 by Xiaomi button"
    use_blueprint:
      path: yuri-vashchenko/button_light_control.yaml
      input:
        trigger_entity: sensor.elena_button_elena_action
        mainlight_entity: light.elena_yeelight
        nightlight_entity: light.elena_yeelight_nightlight
        mode_entity: binary_sensor.elena_yeelight_nightlight
        ambilight_entity: light.elena_yeelight_ambilight
        enabling_entity: binary_sensor.light_control
        hold_action:
          action: script.led_strip_toggle

  - id: "elena_light_control_button_y"
    alias: "elena_light_control_button_y"
    description: "Control Yeelight 650 by Xiaomi button"
    use_blueprint:
      path: yuri-vashchenko/button_light_control.yaml
      input:
        trigger_entity: sensor.elena_button_yuri_action
        mainlight_entity: light.elena_yeelight
        nightlight_entity: light.elena_yeelight_nightlight
        mode_entity: binary_sensor.elena_yeelight_nightlight
        ambilight_entity: light.elena_yeelight_ambilight
        enabling_entity: binary_sensor.light_control
        hold_action:
          action: script.led_strip_toggle

  - id: run_turnoff_script_when_all_hosts_leave_home
    alias: Run the turnoff script when all hosts leave home
    trigger:
      - platform: state
        entity_id: binary_sensor.host_occupancy
        from: "on"
        to: "off"
    condition:
      - alias: "control mode"
        condition: state
        entity_id: binary_sensor.main_control
        state: "on"
    action:
      - alias: "Run turnoff script"
        action: script.turn_on
        target:
          entity_id: script.elena_turn_off_tv_light_ac

  - id: Включить ambilight при включении света
    alias: Включить ambilight при включении света
    trigger:
      - platform: state
        entity_id: light.elena_yeelight
        to: "on"
      - platform: state
        entity_id: light.elena_yeelight_nightlight
        to: "on"
    condition:
      - alias: "main control"
        condition: state
        entity_id: binary_sensor.main_control
        state: "on"
      - alias: "ambilight is off"
        condition: state
        entity_id: light.elena_yeelight_ambilight
        state: "off"
    action:
      - alias: "action alias (name)"
        action: light.turn_on
        target:
          entity_id: light.elena_yeelight_ambilight

  - id: Включить свет когда кто-то зашёл и вечер и темно
    alias: Включить свет когда кто-то зашёл и вечер и темно
    trigger:
      - platform: state
        entity_id: sensor.users_in_elena_room
        from: "0"
        to: "1"
    condition:
      - alias: "control mode"
        condition: state
        entity_id: binary_sensor.main_control
        state: "on"
      - alias: "It is evening"
        condition: state
        entity_id: binary_sensor.evening
        state: "on"
      - alias: "it is dark"
        condition: numeric_state
        entity_id: sensor.elena_motion_illuminance_illuminance_lux
        below: 25
      - alias: "main light is off"
        condition: state
        entity_id: light.elena_yeelight
        state: "off"
      - alias: "nightlight is off"
        condition: state
        entity_id: light.elena_yeelight_nightlight
        state: "off"
      - alias: "motion is detected"
        condition: state
        entity_id: binary_sensor.elena_motion
        state: "on"
    action:
      - alias: "Turn on the light"
        action: light.turn_on
        target:
          entity_id: light.elena_yeelight_nightlight
