esphome:
  name: ble-tracker-mama
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret 'wi_fi_ssid'
  password: !secret 'wi_fi_password'
  manual_ip:
    static_ip: 192.168.0.235
    gateway: 192.168.0.1
    subnet: 255.255.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ble-tracker-mama-fallback"
    password: !secret 'ble_tracker_mama_ap'

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret 'ble_tracker_mama_ota'

ota:
  password: !secret 'ble_tracker_mama_ota'

esp32_ble_tracker:

binary_sensor:
  - platform: ble_presence
    mac_address: FA:C7:AF:ED:9B:5E
    name: mama_watch_papa
    id: mama_watch_papa
    on_state:
      then:
        - if:
            condition: 
              binary_sensor.is_on: mama_watch_papa
            then:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: mama_watch_papa
                    location_name: 'home'
            else:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: mama_watch_papa
                    location_name: 'not_home'
  - platform: ble_presence
    mac_address: D3:CC:FA:54:BA:EB
    name: mama_mi_band4_mama
    id: mama_mi_band4_mama
    on_state:
      then:
        - if:
            condition: 
              binary_sensor.is_on: mama_mi_band4_mama
            then:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: mama_mi_band4_mama
                    location_name: 'home'
            else:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: mama_mi_band4_mama
                    location_name: 'not_home'
  - platform: ble_presence
    mac_address: C0:09:0A:1B:2E:09
    name: mama_mi_band5_michael
    id: mama_mi_band5_michael
    on_state:
      then:
        - if:
            condition: 
              binary_sensor.is_on: mama_mi_band5_michael
            then:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: mama_mi_band5_michael
                    location_name: 'home'
            else:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: mama_mi_band5_michael
                    location_name: 'not_home'
  - platform: ble_presence
    mac_address: F2:54:2A:E6:F8:BD
    name: mama_mi_band6_elena
    id: mama_mi_band6_elena
    on_state:
      then:
        - if:
            condition: 
              binary_sensor.is_on: mama_mi_band6_elena
            then:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: mama_mi_band6_elena
                    location_name: 'home'
            else:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: mama_mi_band6_elena
                    location_name: 'not_home'
  - platform: ble_presence
    mac_address: C1:09:0A:09:4C:4E
    name: mama_mi_band6_yuri
    id: mama_mi_band6_yuri
    on_state:
      then:
        - if:
            condition: 
              binary_sensor.is_on: mama_mi_band6_yuri
            then:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: mama_mi_band6_yuri
                    location_name: 'home'
            else:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: mama_mi_band6_yuri
                    location_name: 'not_home'
  - platform: ble_presence
    mac_address: 5D:41:73:FC:62:60
    name: mama_phone_mama
    id: mama_phone_mama
    on_state:
      then:
        - if:
            condition: 
              binary_sensor.is_on: mama_phone_mama
            then:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: mama_phone_mama
                    location_name: 'home'
            else:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: mama_phone_mama
                    location_name: 'not_home'

  - platform: ble_presence
    mac_address: 9C:E9:51:2A:74:82
    name: mama_phone_papa
    id: mama_phone_papa
    on_state:
      then:
        - if:
            condition: 
              binary_sensor.is_on: mama_phone_papa
            then:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: mama_phone_papa
                    location_name: 'home'
            else:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: mama_phone_papa
                    location_name: 'not_home'

sensor:
  # ble trackers
  - platform: ble_rssi
    mac_address: FA:C7:AF:ED:9B:5E
    name: mama_watch_papa_rssi
  - platform: ble_rssi    
    mac_address: D3:CC:FA:54:BA:EB
    name: mama_mi_band4_mama_rssi
  - platform: ble_rssi
    mac_address: C0:09:0A:1B:2E:09
    name: mama_mi_band5_michael_rssi
  - platform: ble_rssi
    mac_address: F2:54:2A:E6:F8:BD
    name: mama_mi_band6_elena_rssi
  - platform: ble_rssi
    mac_address: C1:09:0A:09:4C:4E
    name: mama_mi_band6_yuri_rssi
  - platform: ble_rssi
    mac_address: 5D:41:73:FC:62:60
    name: mama_phone_mama_rssi
  - platform: ble_rssi
    mac_address: 9C:E9:51:2A:74:82
    name: mama_phone_papa_rssi
