# Кухня

homeassistant:
  # customizations
  customize:
    # Розетки и выключатели
    switch.kitchen_power_strip:
      friendly_name: Удлинитель
      icon: mdi:power-plug
    sensor.kitchen_switch_load_power:
      icon: mdi:gauge
      unit: Вт
    sensor.kitchen_plug_load_power:
      icon: mdi:gauge
      unit: Вт

    # Розетка мультиварки
    switch.plug_multipot_power_outage_memory:
      friendly_name: Розетка mainsrv 65 память отключения

    # Розетка телевизора на кухне
    switch.plug_tv_kitchen_power_outage_memory:
      friendly_name: Розетка телевизора на кухне память отключения

    media_player.yandex_station_ff98f02959560d534ab998c1:
      friendly_name: yandex_station_kitchen

  customize_glob:
    # Сенсоры и датчики
    "*water_leak_kitchen*":
      friendly_name: Кухня утечка воды

    "*motion_kitchen*":
      friendly_name: Кухня движение

    "*motion_illumination_kitchen*":
      friendly_name: Кухня движение освещение

    # Розетки и выключатели
    # Розетка мультиварки
    "*plug_multipot*":
      friendly_name: Розетка мультиварки

    # Розетка телевизора на кухне
    "*plug_tv_kitchen*":
      friendly_name: Розетка телевизора на кухне

    # Кухонный выключатель
    "*.switch_kitchen*":
      friendly_name: Кухонный выключатель

    # Детекторы дыма
    "*smoke_detector_kitchen*":
      friendly_name: Кухонный детектор дыма

# Kitchen power strip - convert power to energy to be able to monitor daily consumption
sensor:
  - platform: template
    sensors:
      kitchen_switch_load_power:
        friendly_name: "Кухонный удлинитель текущее потребление"
        value_template: "{{ state_attr('switch.kitchen_power_strip', 'load_power') }}"

  - platform: integration
    source: sensor.kitchen_switch_load_power
    name: kitchen_switch_energy
    unit_prefix: k
    round: 2

# switches
switch:
  # Prevents turning off the light
  - platform: mqtt
    name: kitchen_hold_light_on
    retain: true
    command_topic: "home/kitchen/light/hold_on"
    state_topic: "home/kitchen/light/hold_on"

  # Prevents turning on the light
  - platform: mqtt
    name: kitchen_hold_light_off
    retain: true
    command_topic: "home/kitchen/light/hold_off"
    state_topic: "home/kitchen/light/hold_off"

binary_sensor:
  - platform: template
    sensors:
      # 'on' when kitchen tv consumes power
      kitchen_tv_power:
        friendly_name: "Kitchen TV power"
        value_template: >
          {%- if states('sensor.plug_tv_kitchen_power') not in ['unknown', 'unavailable']-%}
            {{ states('sensor.plug_tv_kitchen_power') | float > 10.0 }}
          {%- else -%}
            false
          {%- endif -%}

      # Prevents turning on the light
      kitchen_hold_light_off:
        friendly_name: Не включать свет
        value_template: >
          {{ states('binary_sensor.light_control') == 'off' or
            states('switch.kitchen_hold_light_off') == 'on' }}

      # Prevents turning off the light
      kitchen_hold_light_on:
        friendly_name: Не выключать свет
        value_template: >
          {{ states('binary_sensor.light_control') == 'off' or
            states('switch.kitchen_hold_light_on') == 'on' }}

# lights
light:
  - platform: switch
    name: switch_kitchen
    entity_id: switch.switch_kitchen

# TV
media_player:
  - platform: smartir
    name: kitchen-tv
    unique_id: kitchen_tv
    device_code: 1061
    controller_data: remote.remote_broadlink_kitchen
    power_sensor: binary_sensor.kitchen_tv_power

automation:
  - id: kitchen_hold_light_on_timer
    alias: kitchen_hold_light_on_timer
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type:
          - automation_reloaded
      - platform: state
        entity_id: switch.kitchen_hold_light_on
    condition: "{{ states('binary_sensor.light_control') == 'on' }}"
    action:
      - delay:
          minutes: "{{ (states('number.kitchen_hold_light_on_timeout') | int) }}"
      - service: switch.turn_off
        target:
          entity_id: switch.kitchen_hold_light_on
    mode: restart

  - id: kitchen_hold_light_off_timer
    alias: kitchen_hold_light_off_timer
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type:
          - automation_reloaded
      - platform: state
        entity_id: switch.kitchen_hold_light_off
    condition: "{{ states('binary_sensor.light_control') == 'on' }}"
    action:
      - delay:
          minutes: "{{ (states('number.kitchen_hold_light_off_timeout') | int) }}"
      - service: switch.turn_off
        target:
          entity_id: switch.kitchen_hold_light_off
    mode: restart

  - id: auto_turn_light_in_kitchen_on_motion_when_dark
    alias: kitchen_light
    description: ""
    use_blueprint:
      path: kevinxw/state_based_entity_control.yaml
      input:
        trigger_entity: group.motion_kitchen
        target_entity: light.switch_kitchen
        blocker_entity: binary_sensor.kitchen_hold_light_off
        blocker_entity_state: 'on'
        timeout_blocker_entity: binary_sensor.kitchen_hold_light_on
        timeout_blocker_entity_state: 'on'
        illuminance_sensor: sensor.motion_illumination_kitchen_illuminance_lux
        illuminance_below: 14
        sun_elevation_below: 7
        trigger_timeout: 60
        alt_trigger_timeouts: "17:00:00-22:00:00,1200;05:00:00-08:00:00,1200"
