# Кухня. Детектор дыма

homeassistant:
  # customizations
  customize_glob:
    # Сенсоры и датчики
    # Детекторы дыма
    "*kitchen_smoke_detector*":
      friendly_name: Кухонный детектор дыма

mqtt:
  binary_sensor:
    - name: kitchen_smoke_detector
      state_topic: "home/kitchen/smoke_detector"
      payload_on: "on"
      payload_off: "off"

script:
  kitchen_smoke_detector_triggered:
    alias: "Kitchen smoke detector triggered"
    description: "Kitchen smoke detector triggered"
    use_blueprint:
      path: "yuri-vashchenko/event_action.yaml"
      input:
        event_severity: "alarm"
        event_type: "kitchen"
        event_id: "smoke"
        ringtone_id: "2"
        ringtone_volume: "100"
        announcement_message: "Тревога! Дым на кухне"
        wait_entity: binary_sensor.kitchen_smoke_detector
        wait_entity_state: "off"
        delay_between_repeats: 30
        max_repeats: 10
        announcement_message_end: "Тревога на дым отключена"

automation:
  - id: kitchen_smoke_detector_publish_mqtt
    alias: kitchen_smoke_detector_publish_mqtt
    description: "publish MQTT message when smoke detector state changes"
    use_blueprint:
      path: yuri-vashchenko/publish_mqtt_on_entity_state_change.yaml
      input:
        trigger_entity: binary_sensor.kitchen_smoke_detector_smoke
        topic: "home/kitchen/smoke_detector"
        retain: true
        enabling_entity: binary_sensor.main_control

  - id: kitchen_smoke_detector_alarm
    alias: kitchen_smoke_detector_alarm
    description: "Trigger alarm on MQTT message when kitchen smoke detector triggers"
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_smoke_detector
        to: "on"
    condition: "{{ is_state('binary_sensor.sound_control', 'on') }}"
    action:
      service: script.kitchen_smoke_detector_triggered

  - id: stop_alarm_on_cancel_all_button_press
    alias: Stops script execution when "Cancel all button pressed"
    trigger:
      - platform: state
        entity_id: button.cancel_all
        to: "PRESSED"
    condition: "{{ is_state('binary_sensor.main_control', 'on') }}"
    action:
      - alias: "Stop kitchen_smoke_detector_triggered script"
        service: script.turn_off
        target:
          entity_id: script.kitchen_smoke_detector_triggered
