# Кухня. Детектор дыма

homeassistant:
  # customizations
  customize_glob:
    # Сенсоры и датчики
    # Детекторы дыма
    "*smoke_detector_kitchen*":
      friendly_name: Кухонный детектор дыма

binary_sensor:
  - platform: mqtt
    name: kitchen_smoke_detector
    state_topic: "home/kitchen/smoke_detector"
    payload_on: "on"
    payload_off: "off"

script:
  kitchen_smoke_detector_triggered:
    alias: "Kitchen smoke detector triggered"
    description: "Kitchen smoke detector triggered"
    use_blueprint:
      path: "yuri-vashchenko/event_action.yaml"
      input:
        event_severity: "alarm"
        event_type: "kitchen"
        event_id: "smoke"
        ringtone_id: "2"
        ringtone_volume: "100"
        announcement_message: "Тревога! Дым на кухне"
        wait_entity: binary_sensor.kitchen_smoke_detector
        wait_entity_state: 'off'
        delay_between_repeats: "00:01:00"
        max_repeats: 0
        announcement_message_end: "Тревога на дым отключена"

automation:
  - id: kitchen_smoke_detector_publish_mqtt
    alias: kitchen_smoke_detector_publish_mqtt
    description: "publish MQTT message when smoke detector state changes"
    use_blueprint:
      path: yuri-vashchenko/publish_mqtt_on_entity_state_change.yaml
      input:
        trigger_entity: binary_sensor.smoke_detector_kitchen_smoke
        topic: "home/kitchen/smoke_detector"
        retain: true
        enabling_entity: binary_sensor.main_control
  - id: kitchen_smoke_detector_alarm
    alias: kitchen_smoke_detector_alarm
    description: "Trigger alarm on MQTT message when kitchen smoke detector triggers"
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_smoke_detector
        to: 'on'
    condition: "{{ is_state('binary_sensor.sound_control', 'on') }}"
    action:
      service: script.kitchen_smoke_detector_triggered

