# Балкон

homeassistant:
  customize:
    # Влажность и температура
    sensor.balcony_thermometer_temperature:
      friendly_name: Балкон температура
    sensor.balcony_thermometer_humidity:
      friendly_name: Балкон влажность
    sensor.balcony_thermometer_battery:
      friendly_name: Балкон климат

    # Розетка сервера mainsrv
    switch.balcony_plug_mainsrv_power_outage_memory:
      friendly_name: Розетка mainsrv память отключения

    # Датчики
    binary_sensor.balcony_window_left_contact:
      friendly_name: Балкон левое окно
      device_class: window
    binary_sensor.balcony_window_middle_contact:
      friendly_name: Балкон среднее окно
      device_class: window
    binary_sensor.balcony_window_right_contact:
      friendly_name: Балкон правое окно
      device_class: window

  customize_glob:
    # Датчики
    "*158d000541284e*":
      friendly_name: Балкон левое окно
    "*balcony_window_left*":
      friendly_name: Балкон левое окно

    "*158d00054481d7*":
      friendly_name: Балкон среднее окно
    "*balcony_window_middle*":
      friendly_name: Балкон среднее окно

    "*158d000482ffe3*":
      friendly_name: Балкон правое окно
    "*balcony_window_right*":
      friendly_name: Балкон правое окно

    # Розетка mainsrv
    "*158d0003a4a3f2*":
      friendly_name: Розетка mainsrv
    "*balcony_plug_server_main_main*":
      friendly_name: Розетка mainsrv
