# Ленина комната

homeassistant:
  customize:
    # Климат
    sensor.mi_t_e72e001268f1:
      friendly_name: Юра температура
    sensor.mi_h_e72e001268f1:
      friendly_name: Юра влажность

    # Розетка кондиционера
    switch.plug_ac_power_outage_memory:
      friendly_name: Розетка кондиционера память отключения

    # Розетка кондиционера
    switch.plug_tv_lena_power_outage_memory:
      friendly_name: Розетка телевизора 65 память отключения

      # Телевизор
    media_player.tv:
      friendly_name: TV
      device_class: tv

  customize_glob:
    # Кнопки
    "*158d0003d13dca*":
      friendly_name: Лена кнопка
    "*button_elena*":
      friendly_name: Лена кнопка

    "*158d00035846ec*":
      friendly_name: Юра кнопка
    "*button_yuri*":
      friendly_name: Юра кнопка

    # Розетка кондиционера
    "*158d00032d3a92*":
      friendly_name: Розетка кондиционера
    "*plug_ac*":
      friendly_name: Розетка кондиционера

    # Розетка телевизора
    "*158d0003c77e0c*":
      friendly_name: Розетка телевизора 65
    "*plug_tv_elena*":
      friendly_name: Розетка телевизора 65

    # Датчики
    "*158d000460dde9*":
      friendly_name: Дверь на балкон
    "*door_balcony*":
      friendly_name: Дверь на балкон  
      device_class: door

    "*158d000483f52f*":
      friendly_name: Лена дверь
    "*door_elena*":
      friendly_name: Лена дверь
      device_class: door

    "*158d000464d3fc*":
      friendly_name: Лена движение
    "*motion_elena*":
      friendly_name: Лена движение

binary_sensor:
  - platform: template
    sensors:
      ac_power:
        friendly_name: "AC power"
        value_template: >
          {{ states('sensor.plug_ac_power')|float > 80.0 }}

climate:
  - platform: smartir
    name: main_room_ac
    unique_id: main_room_ac
    device_code: 1401
    controller_data: remote.remote_broadlink_elena
    temperature_sensor: sensor.elena_0xe72e001268f1_temperature
    humidity_sensor: sensor.elena_0xe72e001268f1_humidity
    power_sensor: binary_sensor.ac_power

script:
  led_strip_toggle:
    alias: led_strip_toggle
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.remote_broadlink_elena
          device: led_strip
          command: power

  learn_led_strip_toggle:
    sequence:
      - service: remote.learn_command
        data:
          entity_id: remote.remote_broadlink_elena
          device: led_strip
          command: power

  romantic:
    sequence:
      - service: script.led_strip_toggle

scene:
  - name: Movies
    entities:
      light.elena_yeelight_650_nightlight: "on"
      media_player.tv:
        state: "on"
        source: "КиноПоиск: новинки в FullHD"
  - name: Sport
    entities:
      light.elena_yeelight_650_nightlight: "on"
      media_player.tv:
        state: "on"
        source: "Eurosport Player"

automation:
  # Air Conditioner control
  - alias: elena_ac_control
    initial_state: true
    trigger:
      - platform: state
        entity_id: group.doors_elena
        to: 'on'
        for: "00:01:00"
        id: door_opened
      - platform: state
        entity_id: group.doors_elena
        to: 'off'
        for: "00:01:00"
        id: doors_closed
      - platform: homeassistant
        event: start
        id: started
      - platform: event
        event_type:
          - automation_reloaded
        id: started
      - platform: numeric_state
        entity_id: sensor.e72e001268f1_temperature
        above: 27
        for: "00:01:00"
        id: hot
      - platform: numeric_state
        entity_id: sensor.e72e001268f1_temperature
        below: 22
        for: "00:01:00"
        id: cold
      - platform: numeric_state
        entity_id: sensor.e72e001268f1_temperature
        below: 26
        above: 23
        for: "00:01:00"
        id: warm
    condition: "{{ is_state('binary_sensor.main_control', 'on') }}"
    variables:
      in_temp: >
        {{ states("sensor.e72e001268f1_temperature") | float }}
      is_cold: "{{ in_temp < 22 }}"
      is_hot: "{{ in_temp > 27 }}"
      is_worm: "{{ in_temp > 23 and in_temp < 26 }}"
      out_temp: >
        {{ states("sensor.temperature_humidity_street_temperature") | float }}
      doors_state: >
        {{ states("group.doors_elena") }}
      ac_state: >
        {{ states("climate.main_room_ac") }}
      need_off: >
        {{ (doors_state == 'on' or is_worm ) and ac_state == 'on' }}
      can_heat: >
        {{ doors_state == 'off' and out_temp < 10 and ac_state == 'off' }}
      can_cool: >
        {{ doors_state == 'off' and out_temp > 10 and ac_state == 'off' }}        
    action:
      choose:
        - conditions:
            - condition: trigger
              id:
                - started
                - door_opened
                - warm
            - "{{ need_off }}"
          sequence:
            service: climate.turn_off
            target:
              entity_id: climate.main_room_ac
        - conditions:
            # turn on heating on homeassistant start or automation reloaded if cold
            - condition: trigger
              id:
                - started
                - doors_closed
                - cold
            - "{{ is_cold and can_heat }}"
          sequence:
            service: climate.set_temperature
            data:
              entity_id: climate.main_room_ac
              temperature: 30
              hvac_mode: "heat"
        - conditions:
            # turn on cooling on homeassistant start or automation reloaded if cold
            - condition: trigger
              id:
                - started
                - doors_closed
                - hot
            - "{{ is_hot and can_cool }}"
          sequence:
            service: climate.set_temperature
            data:
              entity_id: climate.main_room_ac
              temperature: 16
              hvac_mode: "cool"

  - id: "elena_light_control_button_l"
    alias: "elena_light_control_button_l"
    description: "Control Yeelight 650 by Xiaomi button"
    use_blueprint:
      path: yuri-vashchenko/button_light_control.yaml
      input:
        trigger_entity: sensor.button_elena_action
        mainlight_entity: light.elena_yeelight_650
        nightlight_entity: light.elena_yeelight_650_nightlight
        mode_entity: binary_sensor.yeelight_ceiling4_0x7d7a691_nightlight
        ambilight_entity: light.elena_yeelight_650_ambilight
        enabling_entity: binary_sensor.light_control
        hold_action:
          service: script.led_strip_toggle

  - id: "elena_light_control_button_y"
    alias: "elena_light_control_button_y"
    description: "Control Yeelight 650 by Xiaomi button"
    use_blueprint:
      path: yuri-vashchenko/button_light_control.yaml
      input:
        trigger_entity: sensor.button_yuri_action
        mainlight_entity: light.elena_yeelight_650
        nightlight_entity: light.elena_yeelight_650_nightlight
        mode_entity: binary_sensor.yeelight_ceiling4_0x7d7a691_nightlight
        ambilight_entity: light.elena_yeelight_650_ambilight
        enabling_entity: binary_sensor.light_control
        hold_action:
          service: script.led_strip_toggle
