# Кухня

homeassistant:
  # customizations
  customize:
    # Розетки и выключатели
    switch.kitchen_power_strip:
      friendly_name: Удлинитель
      icon: mdi:power-plug
    sensor.kitchen_switch_load_power:
      icon: mdi:gauge
      unit: Вт
    sensor.kitchen_plug_load_power:
      icon: mdi:gauge
      unit: Вт

    # Розетка мультиварки
    switch.plug_multipot_power_outage_memory:
      friendly_name: Розетка mainsrv 65 память отключения

    # Розетка телевизора на кухне
    switch.plug_tv_kitchen_power_outage_memory:
      friendly_name: Розетка телевизора на кухне память отключения

    media_player.yandex_station_ff98f02959560d534ab998c1:
      friendly_name: yandex_station_kitchen

  customize_glob:
    # Сенсоры и датчики
    "*water_leak_kitchen*":
      friendly_name: Кухня утечка воды

    "*motion_kitchen*":
      friendly_name: Кухня движение

    "*motion_illumination_kitchen*":
      friendly_name: Кухня движение освещение

    # Розетки и выключатели
    # Розетка мультиварки
    "*plug_multipot*":
      friendly_name: Розетка мультиварки

    # Розетка телевизора на кухне
    "*plug_tv_kitchen*":
      friendly_name: Розетка телевизора на кухне

    # Кухонный выключатель
    "*.switch_kitchen*":
      friendly_name: Кухонный выключатель

    # Детекторы дыма
    "*smoke_detector_kitchen*":
      friendly_name: Кухонный детектор дыма

# Kitchen power strip - convert power to energy to be able to monitor daily consumption
sensor:
  - platform: template
    sensors:
      kitchen_switch_load_power:
        friendly_name: "Кухонный удлинитель текущее потребление"
        value_template: "{{ state_attr('switch.kitchen_power_strip', 'load_power') }}"

  - platform: integration
    source: sensor.kitchen_switch_load_power
    name: kitchen_switch_energy
    unit_prefix: k
    round: 2

binary_sensor:
  - platform: template
    sensors:
      # 'on' when kitchen tv consumes power
      kitchen_tv_power:
        friendly_name: "Kitchen TV power"
        value_template: >
          {{ states('sensor.plug_tv_kitchen_power')|float > 10.0 }}

      # Prevents turning off the light
      hold_light:
        friendly_name: Не выключать свет
        value_template: "{{ states('switch.hold_light') }}"

# switches
switch:
  # Prevents turning off the light
  - platform: mqtt
    name: hold_light
    retain: true
    command_topic: "kitchen_light/hold"
    state_topic: "kitchen_light/hold"

number:
  - platform: mqtt
    name: hold_light_timeout
    command_topic: kitchen_light/hold_duration
    state_topic: kitchen_light/hold_duration
    retain: true
    icon: mdi:lightbulb-on
    min: 1
    max: 600

# lights
light:
  - platform: switch
    name: switch_kitchen
    entity_id: switch.switch_kitchen

# TV
media_player:
  - platform: smartir
    name: kitchen-tv
    unique_id: kitchen_tv
    device_code: 1061
    controller_data: remote.remote_broadlink_kitchen
    power_sensor: binary_sensor.kitchen_tv_power
