# Мамина комната

homeassistant:
  customize:
    # Выключатель
    switch.switch_mama_switch:
      friendly_name: Мама выключатель
    light.switch_mama_0x00158d0005440c33:
      friendly_name: Мама свет

    # Розетка телевизора 49
    switch.plug_tv_mama_power_outage_memory:
      friendly_name: Розетка телевизора 49 память отключения

    # Ping
    binary_sensor.printer_hp:
      friendly_name: Принтер hp

    media_player.yandex_station_ff98f029014bad091f5988de:
      friendly_name: yandex_station_mama

    # Влажность и температура
    sensor.temperature_humidity_mama_temperature:
      friendly_name: Мама температура
    sensor.temperature_humidity_mama_humidity:
      friendly_name: Мама влажность
    sensor.temperature_humidity_mama_pressure:
      friendly_name: Мама давление
  customize_glob:
    # Кнопка
    "*158d0003ce386f*":
      friendly_name: Мама кнопка
    "*button_mama*":
      friendly_name: Мама кнопка

    # Выключатель
    "sensor.switch_mama*":
      friendly_name: Мама выключатель

    # Розетка телевизора
    "*158d0001567169*":
      friendly_name: Розетка телевизора 49
    "*plug_tv_mama*":
      friendly_name: Розетка телевизора 49

    # Датчики
    # Датчик движения
    "*158d00044f94f4*":
      friendly_name: Мама движение
    "*motion_mama*":
      friendly_name: Мама движение

    # Влажность и температура
    "*158d0006b1cd57*":
      friendly_name: Мама климат
    "*temperature_humidity_mama*":
      friendly_name: Мама климат

light:
  - platform: switch
    name: light_mama
    entity_id: switch.switch_mama

# switches
switch:
  - platform: mqtt
    name: switch_mqtt_mama
    retain: true
    command_topic: "home/mama/light"
    state_topic: "home/mama/light"
    payload_on: "on"
    payload_off: "off"

automation:
  - id: mama_sync_switches
    alias: "Mama synchronize mqtt and phisical switches"
    trigger:
      - platform: homeassistant
        event: start
        id: started
      - platform: event
        event_type: automation_reloaded
        id: started
      - platform: state
        entity_id:
          - switch.switch_mama
          - switch.switch_mqtt_mama
        id: switch_state_change
    condition:
      - alias: "main control"
        condition: state
        entity_id: binary_sensor.main_control
        state: "on"
    action:
      - alias: "Sync mqtt switch with phisical switch"
        choose:
        - conditions:
            - alias: "on start"
              condition: trigger
              id: started
          sequence:
            - alias: "set mqtt switch to physical switch state"
              service: mqtt.publish
              data_template:
                topic: "home/mama/light"
                payload_template: "{{ states('switch.switch_mama') }}"
        - conditions:
            - alias: "on phisical switch state change"
              condition: trigger
              id: switch_state_change
          sequence:
            - alias: "check for valid states"
              condition: template
              value_template: "{{ trigger.to_state.state in ['on', 'off'] }}"
            - alias: "set mqtt switch to new physical switch state"
              service: "{{ 'switch.turn_' + trigger.to_state.state }}"
              target:
                entity_id:
                  - switch.switch_mama
                  - switch.switch_mqtt_mama
    mode: single
    max_exceeded: silent