# Мамина комната

homeassistant:
  customize:
    # Выключатель
    switch.mama_switch_light:
      friendly_name: Мама выключатель
    light.mama_main:
      friendly_name: Мама - основной свет

    # Розетка телевизора 49
    switch.mama_plug_tv_power_outage_memory:
      friendly_name: Розетка телевизора 49 память отключения

    media_player.yandex_station_ff98f029014bad091f5988de:
      friendly_name: yandex_station_mama

    # Влажность и температура
    sensor.mama_thermometer_temperature:
      friendly_name: Мама температура
    sensor.mama_thermometer_humidity:
      friendly_name: Мама влажность
    sensor.mama_thermometer_pressure:
      friendly_name: Мама давление

  customize_glob:
    # Кнопка
    "*158d0003ce386f*":
      friendly_name: Мама кнопка

    # Выключатель
    "sensor.mama_switch_light*":
      friendly_name: Мама выключатель

    # Розетка телевизора
    "*158d0001567169*":
      friendly_name: Розетка телевизора 49
    "*mama_plug_tv*":
      friendly_name: Розетка телевизора 49

    # Датчики
    # Датчик движения
    "*158d00044f94f4*":
      friendly_name: Мама движение
    "*mama_motion*":
      friendly_name: Мама движение

    # Влажность и температура
    "*158d0006b1cd57*":
      friendly_name: Мама климат
    "*mama_thermometer*":
      friendly_name: Мама климат

light:
  - platform: switch
    name: mama_main
    entity_id: switch.mama_switch_light

script:
  mama_button_single_click:
    alias: Мама - однократное нажатие на кнопку
    sequence:
      - alias: Контроль управления светом
        condition: state
        entity_id: binary_sensor.light_control
        state: "on"
      - alias: Переключить свет
        action: switch.toggle
        target:
          entity_id: switch.mama_switch_light
  mama_button_double_click:
    alias: Мама - двухкратное нажатие на кнопку
    sequence:
      - alias: Переключить телевизор
        if:
          - alias: Состояние телевизора
            condition: state
            entity_id: media_player.mama_tv
            state: "off"
        then:
          - alias: Включить телевизор
            action: media_player.turn_on
            target:
              entity_id: media_player.mama_tv
        else:
          - alias: Выключить телевизор
            action: media_player.turn_off
            target:
              entity_id: media_player.mama_tv
  mama_button_hold_click:
    alias: Мама - длительное нажатие на кнопку
    sequence:
      - alias: Контроль управления звуком
        condition: state
        entity_id: binary_sensor.sound_control
        state: "on"
      - alias: Позвать во всех колонках
        action: script.all_say
        data:
          message: Подойдите в мамину комнату

automation:
  - id: mama_button_click
    alias: Мама - нажатие на кнопку
    trigger:
      - trigger: state
        entity_id: sensor.mama_button_bed_action
        to:
          - single
          - double
          - hold
    variables:
      button_state: "{{ trigger.to_state.state }}"
      script_name: >
        script.mama_button_{{ button_state }}_click
    condition:
      - alias: Контроль управления светом
        condition: state
        entity_id: binary_sensor.main_control
        state: "on"
    action:
      - alias: Запуск скрипта по нажатию
        action: script.turn_on
        target:
          entity_id: "{{ script_name }}"
