# Мишина комната

homeassistant:
  customize:
    # Влажность и температура
    sensor.michael_thermometer_temperature:
      friendly_name: Миша температура
    sensor.michael_thermometer_humidity:
      friendly_name: Миша влажность
    sensor.michael_thermometer_pressure:
      friendly_name: Миша давление

    # Розетка Миша
    switch.michael_plug_power_outage_memory:
      friendly_name: Розетка Миша память отключения

  customize_glob:
    # Датчик движения
    "*158d000465a633*":
      friendly_name: Миша движение
    "*michael_motion*":
      friendly_name: Миша движение

    # Розетка
    "*158d0003c77d8b*":
      friendly_name: Розетка Миша
    "*michael_plug_yuri_*":
      friendly_name: Розетка Юра

    # Влажность и температура
    "*158d0006b11191*":
      friendly_name: Миша климат
    "*michael_thermometer*":
      friendly_name: Миша климат

template:
  - sensor:
      - name: michael_total_power
        state: >
          {% set ns = namespace(states=[]) -%}
          {% for plug in expand('group.michael_plug') | selectattr('domain','eq','switch') | map(attribute='entity_id') -%}
            {% set energy_sensor_name = plug | replace("switch", "sensor") + "_power" -%}
            {% if is_number(states(energy_sensor_name)) -%}
            {% set plug_energy = states(energy_sensor_name) | float -%}
            {% set ns.states = ns.states + [plug_energy] -%}
            {% endif -%}
          {% endfor -%}
          {{ ns.states | sum | round(2) }}
        state_class: measurement
        unit_of_measurement: "W"
        device_class: power

      - name: michael_total_energy
        state: >
          {% set ns = namespace(states=[]) -%}
          {% for plug in expand('group.michael_plug') | selectattr('domain','eq','switch') | map(attribute='entity_id') -%}
            {% set energy_sensor_name = plug | replace("switch", "sensor") + "_energy" -%}
            {% if is_number(states(energy_sensor_name)) -%}
            {% set plug_energy = states(energy_sensor_name) | float -%}
            {% set ns.states = ns.states + [plug_energy] -%}
            {% endif -%}
          {% endfor -%}
          {{ ns.states | sum | round(2) }}
        state_class: total_increasing
        unit_of_measurement: "kWh"
        device_class: energy

automation:
  - id: michael_turn_off_plug_when_note_asus_becomes_unavailable
    alias: "Выключить розетку когда ноутбук становится недоступен"
    description: "Отключает розетку при недоступности ноутбука для экономии электроэнергии"
    trigger:
      - platform: state
        entity_id: device_tracker.a0_ce_c8_ed_8d_45
        from: home
    condition: "{{ is_state('binary_sensor.main_control', 'on') }}"
    action:
      - alias: turn off the plug
        service: switch.turn_off
        target:
          entity_id: switch.michael_plug_yuri
    mode: restart
