# Мишина комната

homeassistant:
  customize:
    # Влажность и температура
    sensor.michael_thermometer_temperature:
      friendly_name: Миша температура
    sensor.michael_thermometer_humidity:
      friendly_name: Миша влажность
    sensor.michael_thermometer_pressure:
      friendly_name: Миша давление

    # Розетка Миша
    switch.michael_plug_power_outage_memory:
      friendly_name: Розетка Миша память отключения

  customize_glob:
    # Датчик движения
    "*158d000465a633*":
      friendly_name: Миша движение
    "*michael_motion*":
      friendly_name: Миша движение

    # Розетка
    "*158d0003c77d8b*":
      friendly_name: Розетка Миша
    "*michael_plug*":
      friendly_name: Розетка Миша

    # Влажность и температура
    "*158d0006b11191*":
      friendly_name: Миша климат
    "*michael_thermometer*":
      friendly_name: Миша климат
