# Улица

homeassistant:
  customize:
    # Влажность и температура
    sensor.street_thermometer_temperature:
      friendly_name: Улица температура
    sensor.street_thermometer_humidity:
      friendly_name: Улица влажность
    sensor.street_thermometer_pressure:
      friendly_name: Улица давление
    sensor.street_thermometer_battery:
      friendly_name: Улица климат
    sensor.street_thermometer_linkquality:
      friendly_name: Улица климат
