# Светина комната

homeassistant:
  customize:
    # Камера
    # binary_sensor.camera_reolink_front:
    #   friendly_name: Камера reolink

    # Влажность и температура
    sensor.svetlana_thermometer_temperature:
      friendly_name: Света температура
    sensor.svetlana_thermometer_humidity:
      friendly_name: Света влажность
    sensor.svetlana_thermometer_pressure:
      friendly_name: Света давление

  customize_glob:
    # Датчики
    "*158d00044f944b*":
      friendly_name: Света движение
    "*svetlana_occupancy*":
      friendly_name: Света движение

    # Влажность и температура
    "*158d0006b110ee*":
      friendly_name: Света климат
    "*svetlana_thermometer*":
      friendly_name: Света климат

# mqtt sensors
mqtt:
  sensor:
    - name: last_event_svetlana_motion_occupancy
      device_class: timestamp
      state_topic: "home/svetlana/svetlana_motion_occupancy/on"

# automations
automation:
  - alias: svetlana_record_last_motion
    description: "Сохраняет дату и время последнего движения у Светы в комнате"
    use_blueprint:
      path: yuri-vashchenko/mqtt_record_event_timestamp.yaml
      input:
        topic: "home/svetlana"
        trigger_entity: binary_sensor.svetlana_motion_occupancy
        enabling_entity: switch.control_mode
        enabling_entity_state: "on"
